boostorg/website-v2

config/urls.py
libraries/api.py
package.json
templates/base.html
templates/libraries/includes/search_command_palatte.html
templates/libraries/includes/search_results.html
templates/libraries/list.html
yarn.lock

* Bootstrapped API viewset to search libraries
* Updated templates
* Added htmx for search
* Search results template to display results
Issue: #88

:tractor: WIP working search

---

static/css/styles.css
templates/forum/forum_list.html
templates/homepage.html
templates/includes/_footer.html
templates/includes/_header.html
templates/libraries/_library_list_item.html
templates/libraries/detail.html
templates/libraries/includes/search_command_palatte.html
templates/libraries/includes/search_results.html
templates/partials/breadcrumb.html
templates/users/profile.html

* Fixes text color regressions
* Adds profile image to profile template
* Adds profile image to library list template
* Adds profile image to library detail template
* Sets a default user icon if no profile image

Images css fixes

---

users/__init__.py
users/apps.py
users/models.py
users/signals.py
users/tests/test_models.py
users/tests/test_signals.py

Add signal to get GitHub profile photo when new user account is created 

---

config/urls.py
requirements.in
requirements.txt
templates/users/photo_upload.html
users/forms.py
users/tests/test_urls.py
users/views.py

Part of #121 
Note: This is pretty bare bones. I didn't try to style it much since I know that there are changes coming to the profile page anyway. 
- New url: `POST /users/me/photo/` where users can upload their own image 
- Redirects back to the user's own profile

✨ User can upload a new profile photo 

---

static/css/styles.css
templates/includes/_header.html
templates/users/photo_upload.html
templates/users/profile.html

* adds link to top menu when authenticated to link to profile
* styles the upload profile photo form
Issue: #127

:sparkles: profile link and photo form style

---

config/settings.py
static/css/styles.css
templates/base.html
templates/board_base.html
templates/forum_conversation/topic_detail.html
templates/includes/_header.html
templates/partials/messages.html

* Fixes permissions on forums so any authenticated user can access
* Adds google search to the site #36 
* Styles the messages #83 
* Adds GitHub style permalinks to forums

Styles and forum fixes

---

libraries/api.py
libraries/tests/test_api.py
static/css/styles.css
templates/libraries/_alphabet_filter.html
templates/libraries/_library_list_item.html
templates/libraries/detail.html
templates/libraries/includes/search_command_palatte.html
templates/libraries/includes/search_results.html
templates/libraries/list.html
templates/versions/list.html

* distinct query
* style adjustments
* tests
Issue: #88

88 library search

---

core/boostrenderer.py
stage_static_config.json

Fix static search bar

---

README.md
docs/development_setup_notes.md

Further instructions about installing the development site on Windows WSL (Windows Subsystem for Linux) and/or Ubuntu 22.04.

Docs: development notes

---

templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/homepage.html
templates/includes/_header.html
templates/libraries/_library_list_item.html
templates/libraries/detail.html
templates/releases_temp.html
templates/socialaccount/login.html

This is getting in the way of branches every time there is a modification on any other template.

Template changes after `pre-commit` checks.

---

config/urls.py
core/tests/test_views.py
templates/privacy_temp.html

Part of #324  
- Creates a temporary Privacy Policy page

:sparkles: Add temp privacy policy page

---

config/urls.py
libraries/tests/test_views.py
templates/libraries/detail.html

Also updated a couple template links to use the query param filtering

:bug: Restore accidentally-deleted URL pattern and test

---

static/css/styles.css
templates/libraries/includes/search_command_palatte.html
templates/libraries/list.html

Fixes spacing on controls for #409

Library issues

---

config/settings.py
docker-compose.yml
news/notifications.py
news/tests/test_notifications.py
news/tests/test_views.py
news/views.py
requirements.in
requirements.txt

This work includes the adding of helpers to send emails (new notifications module).

Send email notifications for news approcal and moderation (Part of #343)

---

core/boostrenderer.py
core/tests/test_renderer.py
core/views.py
docker-compose.yml
requirements.in
requirements.txt

Part of #394 
- Make web service depend on redis 
- Add function to extract body from html content
- In view, extract body before returning converted ascciidoc in response

Extract content of HTML body from rendered asciidoc content

---

.github/workflows/actions-gcp.yaml
.github/workflows/actions.yml
config/settings.py
kube/boost/templates/celery.yaml
kube/boost/templates/configmap-nginx.yaml
kube/boost/templates/deployment.yaml
kube/boost/templates/ingress.yaml
kube/boost/templates/redis.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

Github Actions and Helm templates to deploy:  
- www.boost.cpp.al - future production site. The URL can be changed later. 'main' branch.
- www.stage.boost.cpp.al - a staging site similar to boost.revsys.dev. 'develop' branch.
- cppal-dev.boost.cpp.al - linked to my git fork, internal testing. 
Out of an abundance of caution, since the beta was just released today, let's not merge this pull request until early next week.

Deploy to new environments

---

static/css/styles.css
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html

Instead of slate on charcoal for the selected toggle in dark mode, make it green with white text.
Issue: #421

:sparkles: restyles selected library toggles

---

config/settings.py
config/urls.py
core/views.py
requirements.in
requirements.txt
templates/includes/_header.html
templates/users/includes/user_join.html
templates/users/includes/user_profile_image.html
users/serializers.py
users/views.py

Fetching the header and footer from the site-docs repo (Antora) is working but there is a cors issue with the authenticated user.  I'm merging this into develop so we can run some tests from S3 on a simple HTML file to see if we get the same results.
Issue: #396

Header and footer endpoints

---

frontend/styles.css
static/css/styles.css
templates/docs_temp.html
templates/includes/_footer.html
templates/includes/_header.html
templates/libraries/list.html
templates/news/list.html

UI updates to Learn & News

---

frontend/styles.css
static/css/styles.css
templates/base.html
templates/includes/_header.html
templates/versions/detail.html

resolves #497 
resolves #503 
resolves #511

Go Launch items - Releases, scrollbar, header icons

---

users/migrations/0004_auto_20211105_0915.py

@frankwiles to delete the `forum` tables, I cleared out the DB, and ran migrations again from scratch.  Since you removed a bunch of forum files last week I was hoping this would work. But it crashed.  The reason was probably left-over migrations in `users/migrations/` . I removed those, and db migrations completed.  Please merge this PR if it looks ok.
Another question, have all forum vestiges been deleted?  There might still be some. Checking the files with `grep`:
```
$ grep -r -i forum *
ak/views.py:    Our default homepage for Forum.  We expect you to not use this view
config/wsgi.py:WSGI config for Forum.
frontend/styles.css:  /* Forum style overrides */
static/css/styles.css:/* Forum style overrides */
templates/base.html:      {% comment %}body block is for use in forums{% …
```

Remove user forum migration

---

.pre-commit-config.yaml
README.md
package.json
yarn.lock

This should never run in the CI and i’m not convinced it’s adding much value so removing it completely.
Issue: #530

:hammer: removes rustywind

---

frontend/styles.css
static/css/styles.css
templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/libraries/_library_category_list_item.html
templates/libraries/_library_flat_list_item.html
templates/libraries/_library_list_item.html
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html
templates/news/list.html

resolves #526 
resolves #527 
resolves #515 
resolves #510 
still to add - 
#505
#521 
check into #390

Library Listings, News Icons, Community/Learn Links

---

kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

In the kube files, AWS_S3_ENDPOINT_URL and AWS_S3_REGION_NAME must be set.

Set AWS_S3_ENDPOINT_URL variable

---

config/urls.py
core/tests/test_views.py
frontend/styles.css
static/css/styles.css
templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/includes/_footer.html
templates/libraries/_library_flat_list_item.html
templates/libraries/_library_list_item.html
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html
templates/privacy_temp.html
templates/terms_of_use.html

TOS/Privacy styles from Termly updated a bit but still needs a little work.

Launch Item Updates includes TOS/Privacy

---

templates/users/profile_new.html
users/forms.py
users/tests/test_forms.py
users/tests/test_views.py
users/views.py

Add first name, last name, and email to profile form

---

templates/libraries/includes/version_alert.html

:bug: fixes version alert on detail

---

templates/includes/_header.html

Fixed typo on class name in header

---

static/css/styles.css
templates/libraries/_library_list_item.html
templates/libraries/detail.html

Matching look of Releases page.  In progress.

Library detail updates, matching changes on Releases

---

templates/socialaccount/connections.html
templates/users/profile_new.html
users/views.py

- Add link to social account management from the profile page
- Override allauth templated related to managing social account connections
- Did my best to apply reasonable styles per other pages (cc @gregnewman) 
Profile page: 
Connections page:

Connect social accounts to profile

---

libraries/tests/test_views.py
libraries/views.py

Part of #541 -- filters out versions without libraries from the version drop-down on the library list page 
- the version still works in the query string, so you can still access `/libraries/?q=&category=&version=boost-1-61-0`, but 1.61.0 doesn't appear in the drop-down since it has no libraries 
- Drop-down on the Releases page is the same, all versions showing up. Then at least people can get to the documentation for that release if they need to.

#541 Filter versions without libraries from the drop-down on the library list page 

---

core/htmlhelper.py
core/tests/test_htmlhelper.py
core/tests/test_views.py
core/views.py
templates/base.html
templates/docs_libs_placeholder.html
templates/includes/_header.html

Study to restore legacy docs styles except for the header styling.

---

core/htmlhelper.py
core/tests/test_htmlhelper.py
core/tests/test_views.py
core/views.py
templates/docs_libs_placeholder.html

Expose via query params multiple options for browsing legacy docs.

---

ak/tests/test_default_pages.py
ak/views.py

@4down This adds the most recent release to the homepage context, like we talked about in our meeting

Add most recent version to homepage context

---

libraries/management/commands/import_library_versions.py

Correct the default minimum for the import script

---

static/css/styles.css
templates/libraries/detail.html

Adds a block with maintainer avatars. If there is no avatar it uses font awesome fa-user icon.

Library maintainers

---

static/css/styles.css
templates/account/login.html
templates/base.html
templates/socialaccount/login.html
templates/socialaccount/snippets/provider_list.html

Now shows which login method was used the last time they logged into the site via localstorage.
* Adds the alpine persist plugin
* Adds js to set the localstorage for the method used to login
* Shows badges on the login method saying “last log in”
* Works for Email, GitHub and Google
Issue: #39

:sparkles: adds last login method signifier

---

static/css/styles.css
templates/base.html
templates/docs_temp.html
templates/includes/_header.html
templates/libraries/detail.html
templates/versions/detail.html

Misc updates clearing out locally
- Learn page updates to display
- Hiding bottom of image when shrinking page
- Changing text cols to 1 when shrinking page
- Library Detail Chart using live data
- Chart changes to light/dark mode appropriately
- Releases drop-down changed to match Libraries which solves problem of text overflowing when shrinking page

Library Chart Update, Display Updates

---

static/css/styles.css
templates/community_temp.html
templates/includes/_header.html
templates/libraries/detail.html

Quick fix on Library Chart bg color and fixed text style issue caught on Community

Quick updates to Library Chart colors, Community

---

templates/versions/detail.html

Add title, desc SEO to releases page

---

libraries/views.py
templates/base.html
templates/libraries/category_list.html
templates/libraries/detail.html
templates/libraries/flat_list.html
templates/libraries/list.html

Closes #637 
@4down Are the values for these fields okay with you?

Add SEO description, author fields to Library pages 

---

core/htmlhelper.py
core/views.py

* Cleans up the remnants of the antora header during injection.
* Turns on the dark mode switcher for the user-guide

:sparkles: cleans up antora header

---

static/css/styles.css
templates/base.html
templates/includes/_header.html

Implements a clean mobile navigation with working theme toggle.

Mobile navigation

---

static/css/styles.css
templates/docs_temp.html
templates/homepage.html
templates/includes/_footer.html

- Updated position of images on Learn
- Footer - removed C++ Alliance, maybe temporary? (commented out)
- Includes Homepage changes, shifted items around, brought over the event slider to break up the grid.  Still needs something more.

Update for Learn Image positions, also latest homepage and footer

---

static/css/styles.css
templates/libraries/detail.html

Update lozenge on detail page

---

config/urls.py
docs/README.md
docs/api.md
libraries/management/commands/import_library_versions.py
versions/api.py
versions/tasks.py
versions/tests/test_api.py

Part of #649 
@4down I limited the API endpoint that imports versions to staff users. Is that the right permission level?

Add api endpoint for release manager

---

frontend/styles.css
static/css/styles.css
templates/account/login.html
templates/account/signup.html

- Adds our styles to the links
- Adds spacing between "remember me" and checkbox
- Makes the remember me label clickable to toggle checkbox + style on checkbox to be cursor-pointer
resolves #666

Added styles to the links + misc tweak

---

static/css/styles.css
templates/includes/_footer.html
templates/includes/_header.html
templates/libraries/_library_category_list_item.html
templates/libraries/_library_flat_list_item.html
templates/libraries/_library_list_item.html
templates/libraries/includes/search_input.html
templates/libraries/includes/search_results.html

- Style tweaks on Library Search Results div to better distinguish it from the background
- Commented out the "no results" for now, not sure if we really need it anyways
- Footer - style tweaks to make it look a little better
- Header - forcing a:visited to use text-inherit to see if it fixes issue for Vinnie on docs site
- Lozenge tooltips changed to have C++ instead of CPP
resolves #672 
resolves #673 
resolves #674 (possibly)

Lozenge text, lib search res, footer, header

---

static/css/styles.css
templates/homepage.html
templates/privacy_temp.html
templates/terms_of_use.html

Stripped all of the Termly tags and reformatted TOS/Privacy Policy pages.  Style updates on homepage.
resolves #679, resolves #660, resolves #661

Updates to TOS/Privacy Policy, minor homepage update

---

docs/README.md
docs/examples/.gitmodules.example
docs/examples/README.md
docs/examples/libraries_multiple.json
docs/examples/libraries_single.json

Adds some examples of `libraries.json` and `.gitmodules` files to the docs for easier reference

Add example files

---

config/urls.py

doc is the correct path for the proper header injection on docs

:bug: fixing route for docs

---

static/css/styles.css
templates/community_temp.html
templates/libraries/detail.html

resolves #704, resolves #705
Updates maintainers to display full name, styles updated for when user has custom profile image to match the placeholder user image.

Maintainers and Community Page

---

frontend/styles.css
static/css/styles.css
templates/libraries/detail.html

Makes readme in library detail pretty
Issue: #698

698 library readme

---

users/views.py

Update message when user has unclaimed account

---

static/css/styles.css
templates/homepage.html
templates/libraries/detail.html

Cleaning up the Maintainers section on homepage for Featured Library (made font smaller and moved that over to library detail also), and began addressing the Recent News on homepage.  
More updates on recent news coming, this is an initial step to clean that area up.

Homepage Maintainers + News

---

static/css/styles.css
templates/libraries/detail.html

Restoring lost changes on library detail.

Library Detail restore

---

templates/libraries/includes/version_alert.html

Change version alert message for beta releases

---

config/urls.py
templates/account/login.html
users/views.py

Change color of alert when existing contributor tries to create an account

---

templates/versions/detail.html
versions/views.py

Fix version detail heading for beta release

---

config/settings.py
core/boostrenderer.py

- Addes `STATIC_CONTENT_MAPPING` environment mapping that defaults to the current `stage_static_config.json`
- Fixes #725

Use static content mapping JSON file from the env

---

static/css/styles.css
templates/homepage.html
templates/includes/_footer.html

Removal of Slack button from homepage

---

docs/README.md
docs/news.md
news/views.py
templates/news/create.html
templates/news/list.html
templates/news/moderation.html

Fixes #779 
Also adjusted the list template to show a link if the user is a moderator to where they can actually do moderation. 
@gregnewman or @4down you should spin through the moderation flow to make sure you're ok with the visual elements. 
Also added some simple docs on what constitutes "published" for a news item and who can moderate.

779 hide news polls

---

news/views.py
templates/news/_entry_form.html
templates/news/detail.html

Removes social icons
Adds cancel button

Misc news fixes

---

static/css/styles.css
templates/includes/_header.html
templates/news/list.html
templates/users/profile_base.html

- Avatars fixed for Issues: #774, #778

WIP News UI/UX effort

---

static/css/styles.css
templates/news/list.html

If the user is a moderator use six columns otherwise use five columns on the news toolbar.
Issue: #813

:bug: conditional columns

---

config/urls.py
static/css/styles.css
templates/style_guide.html

Style guide

---

static/css/styles.css
templates/news/detail.html
templates/news/list.html

* On the news listing the images are removed
* On the news listing page the author name and publish date are on the top right of the cards for desktop and in the footer on mobile.
* On the detail page the image will show and the author name and publish date show next to the avatar.
Issue: #769

:sparkles: Adds author name and publish date to entries

---

core/templatetags/text_helpers.py
static/css/styles.css
templates/homepage.html
templates/news/detail.html

- Deal with the long text in news on the homepage (still to do on news listing page)
- Testing solution for making URLs in posts clickable on detail page
Also has some small style tweaks on homepage to fix spacing between sections.

Update for long text in news on homepage, testing links

---

news/tests/test_views.py
static/css/styles.css
templates/homepage.html
templates/news/list.html
templates/style_guide.html

- Makes URLs into links on news listings on homepage and news listing
- Truncates text on the news listing page
- Added link styles on news listing
- Added avatars (header sized) into style guide
Responsiveness needs tweaking on news listing
resolves #837 
resolves #831 
resolves #800 
resolves #798

Ss remaining news url items

---

static/css/styles.css
templates/homepage.html
templates/news/list.html

- Truncatechars closes HTML tags, truncatewords does not
- Added author name on homepage news items

Addressing issue of entry content truncation occurring inside HTML tag

---

versions/tasks.py

Part of #848 
Not sure what's going on in staging, but hopefully this will help?

Refactor into more tasks

---

static/css/styles.css
templates/news/list.html

* Fixes truncate on news paragraphs
* right aligns name/date and sets explicit width

:bug: fixing truncate

---

core/htmlhelper.py
core/tests/test_htmlhelper.py
versions/releases.py

Add logging, add exception handling

---

users/forms.py
users/models.py
users/tests/test_forms.py
users/tests/test_models.py

Change profile photo filename

---

config/urls.py
support/views.py
templates/includes/_header.html

We are not using this page so I’m removing the route, app and template
Issue: #548

:hammer: Remove support route and template

---

static/css/styles.css
templates/community_temp.html
templates/includes/_footer.html
templates/style_guide.html

resolves #884 
resolves #883 
Quick merge of these two new issues, Slack panel in Community and footer text for C++ Alliance w/link.
Also in this PR, an update to the style guide for the footer as a whole -  since the main footer links do not use the overall site style for links (rightfully so in my opinion).  Though the C++ Alliance link below does use it.  To account for this exception on the link style, it made sense to add this in.

Added Slack to community and footer includes funding message

---

core/views.py

Add to conditional the content type of `"text/html; charset=utf-8"`
Issue: #872

:bug: fixes docs header for 1.84.x

---

libraries/admin.py

Part of #900, makes debugging easier

Add docs url to admin list view

---

libraries/tasks.py

Part of #900 
Note: Commit https://github.com/cppalliance/temp-site/commit/c9cc3c49b32cedabeaa54237b53674ab29bf1332 was also part of #900 but I didn't realize I wasn't on a branch and pushed straight to `develop`. Sorry! 
See gist: https://gist.github.com/williln/3a21931bb050e3394fb7a581eb792734?permalink_comment_id=4877288#gistcomment-4877288
> Detail -
> The docs are available at this URL, and on multiple past versions also.
> https://www.preview.boost.org/doc/libs/boost_1_84_0/libs/detail/doc/html/index.html
> https://www.boost.org/doc/libs/1_84_0/libs/detail/doc/html/index.html
Done in commit https://github.com/cppalliance/temp-site/commit/c9cc3c49b32cedabeaa54237b53674ab29bf1332 
> WinAPI -
> The docs are available at this URL and on multiple past versions also.
> …

Add exception logic for WinAPI, add S3 check for valid docs

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py
versions/tasks.py

Add exception logic for Any library docs 

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Add exception logic for older Call Traits docs

---

libraries/tasks.py

Add exception logic for older Type Traits docs

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Add exception logic for older Dynamic Bitset docs

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Add exception logic for older Compressed Pair docs

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Add exception logic for older Interval docs

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Fix exception logic -- html vs htm

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Part of #900 
Fixes docs urls uploads for: 
- Circular Buffer 
- Detail 
- Enable If 
- Graph Parallel 
- Identity Type 
Add functionality to specify a non-standard library slug

900 bugsfixes

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Part of #900 
Contains exception logic for docs in these libraries: 
- Typed In Place 
- Math Common Factor
- Math Octonion
- Member Function

Add more exception logic for docs urls 

---

kube/boost/templates/celery.yaml
kube/boost/templates/deployment.yaml
kube/boost/templates/migration-job.yaml
kube/boost/values-cppal-dev-gke.yaml

Miscellaneous updates - comment out revsys-docker-registry imagePullSecrets which are causing k8s errors.

Switch cppal-dev env. back from Ingress to Gateway

---

libraries/tasks.py

Fix GraphParallel, IO, and Iterator docs links

---

static/css/styles.css
templates/homepage.html

- Instead of an embed for the featured video, it is now a direct external link.  Used the styling of the event schedule and moved it in between the library spotlight and news to fit in better with that choice.  
- Includes responsive text updates that had not been pushed prior, and the same updates are applied to the external video link.
resolves #961

Homepage - Featured Vid->external link and responsive text.

---

templates/includes/_footer.html

- Fixed typo with URL.  
- Reduced redness in cheeks.

Fixed link URL for license

---

libraries/constants.py
libraries/tasks.py
libraries/tests/test_tasks.py

Part of #900 
- Create a constants file for the library exceptions
- Add version docs missing constant and logic
- Add function to check if version docs are missing
- Add range to missing library-version docs
- Add function to check if library-version docs are missing

Integrate the missing_docs bool into the docs upload process 

---

templates/base.html
templates/markdown/terms-of-use.md
templates/markdown_template.html

- TOS wording updated
- Styles for MD pages added

TOS update / MD page formatting

---

templates/markdown/terms-of-use.md

- Typo addressed
- Change in wording in regards to contributions / harming of minors
- Addition of text about notifying registered users via email of changes
- Last Updated Date

Updated TOS

---

static/css/styles.css
templates/homepage.html

- Made adjustments with the margins and padding between the lines of text
- Adjusted spacing between the hero section and the rest of the page at desktop sizes
- Adjusted font sizes at breakpoints to keep it distinct from the existing text, since that text is meant to flow together, while still maintaining its prominence

Tightened up "proposed for" area in the homepage hero section 

---

users/forms.py

This pull request resolves #912.

Fixes #912

---

news/models.py

Improve clarity of multiple news items. This should fix a user-reported bug related to English grammar.

Update verbose_name_plural in News model

---

core/htmlhelper.py
templates/includes/_header.html

- Fixes #990. 
- Also improved TOC layout for pages like `/doc/libs/boost_1_84_0/libs/container_hash/doc/html/hash.html`.

 add max-height to header, for consistient doc rendering

---

.github/workflows/actions-gcp.yaml
.github/workflows/actions.yml
config/settings.py
docs/env_vars.md

Potential fix for #975

---

libraries/utils.py
libraries/views.py

Improve redirect logic surrounding libraries page

---

config/urls.py
core/views.py

This pull request adds additional redirects to the web application, in support of #1042.

Additional Redirects (#1042)

---

config/urls.py
core/views.py

Fixes tools/{libname}/{path} redirect rules #1055

---

frontend/styles.css
static/css/styles.css

Remove background highlight from code tags on releases page

---

libraries/views.py
templates/libraries/detail.html
templates/versions/detail.html
versions/views.py

Solves the first part of https://github.com/boostorg/website-v2/issues/1039
Probably after this Issue 1039 can be set to a lower priority such as priority 3.  IMO it's still very interesting to work on, however not sure which method is the best.

Remove csrf_token from two pages

---

templates/includes/_header.html

This PR allows the search icon and its functionality for mobile screens. It leverages Alpine.js to reveal the icon based on the users browser width. 
Solves: #740 
https://github.com/boostorg/website-v2/assets/3632378/d5291c28-fc55-4faa-a3cd-56a80ea9126b

Add search button to mobile view

---

templates/community_temp.html

Fixes [#1087 ](https://github.com/boostorg/website-v2/issues/1087#issuecomment-2160032499)

Update discussion policy with relative link in community template

---

kube/boost/templates/configmap-nginx.yaml

Might be more needed here, but here's a first pass of the redirect logic.

Update nginx config with URL redirects and media location

---

libraries/forms.py

This pull request aims to solve #1061.

Remove non-released versions from version selection form queryset

---

config/urls.py
core/views.py

This pull request closes out two remaining redirects for #906.

Additional Redirects

---

versions/management/commands/import_release_notes.py

add commands to Import and process release notes for all available versions

---

requirements.txt

Update dependencies in requirements.txt

---

templates/homepage.html

WIP:  add link to all events in the schedule

---

templates/homepage.html

This pull request aims to solve #1123.

add anchor link to homepage for schedule

---

templates/docs_temp.html

**Fixes Issue:** #1154
**Changes:**
- User Guide:
- Removed Library Names & Organization and Header & Compiled Binaries links
- Added Introduction to the User Community link
- Contributor Guide:
- Updated broken Design Guide Link
- Added Getting Involved, Super-Project, and Introduction to the Contributors Community links
- Updated Libraries to Library Requirements
- Removed Licenses, Portability, Code Organization links
**Testing:**
- Manual device (iPhone 12 Pro) testing
- Manual dev tools testing
**Preview:**

Update Learn section highlights (#1154)

---

frontend/styles.css
templates/includes/_header.html
yarn.lock

header and site colors update

---

templates/base.html
templates/includes/_header.html

removes spacing issues at top of the relative positioned nav bar

header spacing fix

---

frontend/styles.css
templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/includes/_header.html
templates/news/list.html
templates/versions/detail.html
versions/models.py
versions/tests/test_models.py

header matching desktop to mobile (except libraries) and documentation link fix #1172

documentation link fix, mobile/desktop alignment match

---

templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html
templates/versions/detail.html

Smoothes transitions to and within mobile in the libraries, and standardizes height of the releases dropdown.

mobile fixes and alignment for libraries and releases

---

templates/base.html
templates/includes/_header.html
templates/libraries/_library_category_list_item.html
templates/libraries/_library_flat_list_item.html

also includes some minor fixes in libraries

single navbar for desktop and mobile

---

templates/base.html
templates/includes/_header.html

replaces the icons in mobile view with a dropdown navigation

mobile navbar dropdown

---

templates/includes/_header.html

fixes dark mode
spacing alignment changes
pop up nav will disappear shortly after leaving

small tweaks to the mobile nav

---

templates/homepage.html
templates/libraries/_library_list_item.html

UI changes to homepage and libraries grid view. for issue #1205

CSS changes

---

templates/base.html
templates/includes/_header.html

adjusted differences in the layout of the header in the V2-website and the v2-docs

navigation fixed across sites

---

config/celery.py
config/settings.py
docker-compose.yml
requirements.in
requirements.txt

Hopefully going to make your day with this PR.  The first commit is somewhat, but not entirely related changes. 
The actual fix is in the second commit changing the single Django setting.

Redis connections fix

---

templates/homepage.html
templates/includes/_footer.html
templates/includes/_header.html

1. removed tailwind references
2. changed footer link reference
3. extended mobile menu time
4. added system preference to theming and simplified process.

header tailwind removal

---

static/css/boostbookV2.css
templates/includes/_header.html

tweaks to fix antora header

---

templates/homepage.html
templates/includes/_header.html

- adds border and shadow to header help dropdown
- better spaces download button at the bottom
- removes the extra size expansion
- better spaces the large text
- adds same card shadow as seen in other pages

Home page and header fixes

---

frontend/styles.css
static/css/boostbookV2.css
templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/includes/_header.html
templates/libraries/_library_list_item.html
templates/libraries/category_list.html
templates/libraries/detail.html
templates/libraries/flat_list.html
templates/libraries/list.html
templates/news/list.html
templates/style_guide.html
templates/versions/detail.html

standardization of mobile views and some requested header changes

standardized mobile views, header menu changes

---

core/htmlhelper.py

wrap only the body in the injection not the entire injection which includes heading (#1183)

Wrap injection body

---

core/htmlhelper.py

wrap injection based on neighbours, not expected contents

Neighbours based injection wrapping

---

templates/base.html
templates/community_temp.html
templates/docs_libs_placeholder.html
templates/includes/_footer.html
templates/includes/_header.html
templates/libraries/_library_list_item.html
templates/news/list.html

adds visual mapping to asciidocs (not colors)
fixes footer issues (#1268)
fixes giant "B" on load (#1267)
Misc other layout fixes

footer, ascidocs layout, misc

---

templates/includes/_header.html

changes  to reduce styling to asciidocs layouts

removed excess styling from ascii docs

---

frontend/styles.css
static/css/boostbookV2.css
templates/libraries/_library_list_item.html
templates/libraries/category_list.html
templates/libraries/detail.html
templates/libraries/flat_list.html
templates/libraries/includes/library_preferences.html
templates/libraries/list.html

fixes some alignment issues on the library pages

library alignment issues

---

config/settings.py
config/urls.py
docs/development_setup_notes.md
requirements.in
requirements.txt
templates/account/email_confirm.html
templates/account/signup.html
templates/account/verification_sent.html
templates/socialaccount/snippets/provider_list.html
users/views.py

Includes email for various signup/login related events which we'll need to ensure there's support for in staging and prod

Updated login flow to match Figma (#1167, #1128)

---

templates/includes/_footer.html

fixes footer links UI and background issue

link and background fixes

---

templates/includes/_header.html

fixes issues conflicting with boostlook

removed unneeded code

---

libraries/admin.py
versions/admin.py

Wrap staff-only views in admin_view

---

templates/libraries/detail.html
templates/partials/avatar.html

Update avatar appearance

---

requirements.txt
yarn.lock

This is related to #1182, fixes dependabot security issues.

Update JS and Python packages

---

config/urls.py
templates/docs_libs_placeholder.html
templates/includes/_header.html
users/views.py

Related to #1307, couldn't reproduce that specific issue, but did see an issue with the avatar sizing and styling, so added tailwind to docs template

Resolve issue with avatars on docs/guide page

---

templates/includes/_header.html

footer width and TOC height fixes

---

core/tests/content/accumulators.html
core/tests/content/leaf.html
core/tests/fixtures.py
core/tests/test_views.py
core/views.py
frontend/styles.css
templates/docsiframe.html

Related to ticket #1358, libraries docs iframe
~~This also contains some of the work for refactoring away from version selects being copy pasted everywhere.~~ Removed for now, had side effects.

Show asciidocs library docs in iframe

---

libraries/admin.py
libraries/forms.py
templates/admin/library_report_full_detail.html
templates/admin/release_report_detail.html

Add mailing list stats to full and release reports.

---

core/htmlhelper.py

Div id=footer for copyright hidden on release page only

---

config/urls.py
templates/includes/_form_input.html
templates/users/delete.html
templates/users/profile.html
users/forms.py
users/models.py
users/views.py

Option to delete user data

---

libraries/views.py

This is related to ticket #1397

Fix reversion to previous library versions (#1397)

---

libraries/admin.py

Make CommitAuthor admin sortable on name.

---

core/htmlhelper.py
libraries/forms.py
libraries/models.py
templates/admin/release_report_detail.html

Add release notes to release report

---

frontend/styles.css
templates/libraries/_library_list_item.html

fixed spacing between author avatars, iframe background color, and iframe overlapping header shadow

minor UI fixes

---

config/settings.py
core/context_processors.py
docstailwind.config.js
static/css/boostbookV2.css
tailwind.config.js
templates/base.html
templates/includes/_header.html
userguidetailwind.config.js

Use serif fallback for fonts in dev

---

config/settings.py
config/urls.py
templates/versions/in_progress_release_notes.html
versions/releases.py
versions/tasks.py
versions/views.py

- fixes #1155
- add in-progress release notes import to the import_release_notes task

Import and add in-progress release notes.

---

libraries/admin.py
libraries/forms.py
libraries/tasks.py
templates/admin/library_change_list.html
templates/admin/report_polling.html

Generate reports asynchronously

---

libraries/views.py

Fixes the sort order for libraries.
Tests and maybe some refactoring to come with the changes to urls I'm doing.

Fix for library version sort order

---

templates/base.html
templates/community_temp.html
templates/includes/_footer.html

covers #1424, #1425, #1426 
Updated font-awesome to support the new bluesky icon

icons links, font-awesome updated

---

templates/libraries/includes/library_preferences.html

this fixes the issue of the hover text being covered by the cards

Fix library hover text

---

versions/releases.py

- if the adoc version does not exist in S3, fallback to the old process of fetching the html release notes from the boostorg repo
- fixes #1066

Attempt to fetch adoc version of release notes

---

libraries/forms.py
templates/admin/release_report_detail.html

Filter out libraries with 0 commits from release report.

---

libraries/forms.py
templates/admin/release_report_detail.html

Add download links to boost files in release report

---

libraries/forms.py
templates/admin/release_report_detail.html

Add contribution graph to release report.

---

templates/admin/release_report_detail.html

Check if image exists before getting url

---

libraries/forms.py
libraries/utils.py
templates/admin/release_report_detail.html

Add slack activity to release report.

---

libraries/forms.py
templates/admin/release_report_detail.html

Hide slack activity page if there is no activity.

---

static/css/components.css
templates/includes/_header.html

#1511  - corrected background var color and removes header on any modal content

removes header and background color fixed

---

libraries/github.py

- Log an error any time the repo cloning does not return the expected message.
- Fix import of singular line/file changes.

Add logging within commit update task.

---

templates/admin/library_report_base.html
templates/admin/release_report_detail.html
templates/includes/_css_variables.css
templates/includes/_footer.html
templates/includes/_header.html
templates/includes/_social_icon_links.html

Add social icons to release report

---

templates/admin/release_report_detail.html

Styling fix for library index in firefox

---

slack/management/commands/fetch_slack_activity.py

- fixes #1545
- Multiple messages can have the same thread_ts if the message reply is a "thread_broadcast" subtype (the user selected "also send to #channel")
- Use get_or_create on when creating threads and skip broadcasted messages when processing threads to avoid double counting.

Fix creation of multiple Threads

---

frontend/styles.css

minor change to comment to fix dev

comment change

---

core/views.py
static/js/theme_handling.js
templates/includes/_header.html

* Made theme switching class functionality work for asciidoc based docs (#1547)
* Hides footer on all docs

Asciidoc doc pages theme switching/footer hiding

---

core/tests/test_nginx_redirects.py
core/views.py
kube/boost/templates/configmap-nginx.yaml

Add test ensuring nginx redirect map points to valid urls

---

config/settings.py
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

The variable MAILMAN_CORE_DATABASE provides the name of the mm3 core database.  That contains data such as:  
- the `address` table,`verified_on` column, to determine new subscribers during a time period.

Set variable: mailman core db

---

templates/homepage.html
templates/news/create.html
templates/news/list.html

- News item type icons added to homepage news
- External links get external link icons
- Avatars use our avatar tag, so they match styling of other avatars and link to the author's GitHub page
Fixes #1588

News item-related fixes and improvements

---

templates/libraries/detail.html
templates/libraries/includes/dev_master_links.html
templates/libraries/includes/library_preferences.html

Created  icons per Requirement, will pass back to @daveoconnor for the links
Screenshots:
Hover Effects:

UI changes to allow for  icons

---

templates/admin/change_list.html
templates/admin/delete_selected_confirmation.html

This PR adds allowing an admin user to check checkboxes in the admin interface that are retained from page to page for that model item.

Added multipage selection for checkboxes on admin pages (#1555)

---

libraries/forms.py
templates/admin/release_report_detail.html

This is related to #1616.
Also includes changes related to the slack pages from the call on Monday, 10th of February.

Release report slack pages changes

---

libraries/forms.py

Pre-commit did a modification and I somehow didn't notice when doing the --push, so missed these tweaks.

#1634 Multi-page Release Report tweaks (#1632) - PR tweaks

---

templates/account/signup.html

the buttons and checkbox needed more contract. Also added a required asterisk

improve legibility for sign up screen in dark mode refs #1660

---

templates/admin/release_report_detail.html

Made fiscal committed images grayscale (#1680)

---

libraries/migrations/0020_repopulate_slug_20240325_1616.py

This is to fix the error mentioned in https://github.com/boostorg/website-v2/pull/1602
I also had the error while working on another ticket, but this should probably be separate because that PR will be a more involved merge.

Fix: bad migration.

---

docs/scripts/deploy-website.sh

Keeping in mind, if there is a code freeze, the script should not be run (as-is). Since it will deploy website-v2.

Scripts to deploy website, via 'git push'

---

config/urls.py
core/tests/content/leaf.html

Change to point to /doc/formal-reviews/submissions.html

Update URLs pointing to /reviews refs #1659

---

news/views.py
templates/news/detail.html

Add buttons for newer/older news entries within category

---

ak/tests/test_default_pages.py
ak/views.py
libraries/mixins.py
libraries/views.py
templates/homepage.html

display user icons on the homepage library spotlight refs #1658
Re-use the code written for the library detail page for displaying authors and maintainers on the homepage. To avoid duplicating code, moved all the necessary pieces to a mixin to be used by HomepageView and LibraryDetail, and adjusted it to work for both.

Display user icons on the homepage library spotlight

---

templates/homepage.html

https://github.com/boostorg/website-v2/issues/1644

use better arrow for homepage events, add hover effect refs #1644

---

kube/boost/templates/celery.yaml

I manually adjusted these settings last week but it should be checked in.

Increase CPU and memory on celery-worker

---

users/models.py

Fix issue with user avatars

---

libraries/forms.py
reports/generation.py
templates/admin/release_report_detail.html

Fixes:
- Alignment issue on cover page
- Mailing list post chart
- Mailing list subscriber chart

Report mailing list fixes

---

frontend/styles.css
templates/base.html

expands docs area in current doc page

makes docs wider

---

config/celery.py
core/githubhelper.py
users/tasks.py

Added daily task to update user photos from github profiles, bug fixes. 
This is related to ticket #1853.

Refresh user photos from github profiles (#1853)

---

libraries/forms.py
templates/admin/release_report_detail.html

Added "New Libraries" page to release report

New Libraries page in release report

---

templates/libraries/detail.html

Made dependency mentions on library detail pages into links (#1854)

---

.github/workflows/actions-gcp.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

The variable is used in redirects.

Determine boostLatestRelease in GHA
