boostorg/website-v2

versions/tests/fixtures.py
versions/tests/test_views.py
versions/views.py

Broke this out of https://github.com/revsys/boost.org/pull/108 to make that PR more manageable. 
- Reorders the versions on the version list page in descending order by `release_date`

Order older versions by release date, descending 

---

config/urls.py
libraries/tests/test_views.py
libraries/views.py

Broken off from #108 
- Adds `versions/<slug:version_slug>/<slug:slug>/` to load a library for a specific version 
- Adds `versions/<slug:version_slug>/libraries/` to load all libraries for a specific version 
- Adds `versions/<slug:version_slug>/libraries-by-category/<slug:category>/` to load all libraries for a specific version and a specific category

Libraries by version views

---

justfile

I would consider renaming `env.template` to lead with a `.` so that other env tooling will work with it. `.env.example` is probably the more common naming pattern but that takes a docs update too.

:tractor: Fixes name

---

templates/libraries/list.html

Closes #100 cc @gregnewman -- I just had some changes in that template so I added this fix really fast. Let me know if it wasn't what you had in mind.

:bug: Hide "Categorized" in breadcrumb if no category

---

static/css/styles.css
templates/versions/detail.html
templates/versions/list.html
versions/views.py

@gregnewman Wanted to run this by you -- realized the version details page was showing "Current Version" undconditionally. I made it toggle between "current version" and "past version" to mimic how we do the list page: 
Do we want to think about using orange (or something else) instead of green for past versions, to make it more obvious if they are on an older version?

:wrench: Only show 'current version' if it's actually the current version

---

config/urls.py
libraries/github.py
templates/users/photo_upload.html
users/models.py
users/tasks.py
users/tests/test_tasks.py
users/tests/test_urls.py
users/views.py

- Adds URL and view to provide a way for a user to ask that we import their GH profile 
- Adds a celery task to retrieve their user info from the GH API 
- Celery task gets the `avatar_url` from the GH response and calls the User model method that saves an image from a URL 
- Adds a button on the "Update profile photo" page that the user can click to update their profile photo

#121 Allow user to import their GH profile photo 

---

core/boostrenderer.py

Per @frankwiles, for `.js` files, force the content_type to `application/javascript`

Force content type for js static content

---

libraries/models.py

Part of #252 
- Changes the display value of `cxxstd` for "03". Seems like the chart I was working from had some formatting errors.

:pencil: Change the display value of cxxstd 03

---

docs/commands.md
libraries/github.py
versions/management/commands/import_versions.py

Part of #168 
- Allows existing versions to be skipped when importing 
- Allows a GitHub API token to be passed to the management command (as a way to get around needing to set one for now, this will let me use mine in staging without setting it as the permanent value in staging)

:pencil: Add options for skipping existing versions, passing API token

---

templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/libraries/detail.html
templates/libraries/list.html
templates/news/detail.html
templates/news/list.html
templates/releases_temp.html
templates/support/contact.html
templates/support/getting_started.html
templates/support/support.html

#308
- Adds base title `Boost` to `base.html` which is used when no title specified
- Adds specific titles to major pages (probably need to be added to translations?)

templates: Add base title Boost and some specific titles to major pages

---

justfile

@nessita When I pulled your changes to the `justfile` in, I got errors related to `ARGS`  when I ran `just shell`, `just test`, etc. Looks like it just needed a default value.

Add default ARGS value

---

config/urls.py
news/forms.py
news/models.py
news/tests/fixtures.py
news/tests/test_forms.py
news/tests/test_models.py
news/tests/test_views.py
news/views.py
templates/news/detail.html
templates/news/form.html
templates/news/list.html

More for #273: this branch provides a new form and view to create news (limited to authenticated users). For now, every new entry, requires moderation. Approval can be done via the web UI when visiting a news detail page and having the right permissions.
Next branch would provide:
* moderator whitelisting
* news list needing moderation view
* email sending on news submission

Provide News creation and approval views.

---

config/urls.py
libraries/tests/test_views.py
libraries/views.py
templates/libraries/list.html

- Adds `/libraries/by-category`
- Uses the same template `list.html` as the existing list view. @gregnewman when you have a custom template, though, you can replace `libraries.views.LibraryListByCategory.template_name`. In the meantime, there is a template var `by_category` that you can key off of. 
The sorting is ugly but present 😬

:sparkles: Add libraries by category view

---

config/urls.py
libraries/tests/test_views.py
libraries/views.py
templates/libraries/list.html

- Add `/libraries/mini/` and `/libraries/by-category/mini/` 
- @gregnewman both of these are ultimately just subclasses of `libraries.views.LibraryList`, so the category and version filtering should still work if you need it. The form action for the filtering is manually set to `/libraries/` and I didn't change it yet -- will these pages also need the same version and category filtering as the others? If so, I'll make a new PR that corrects the form action so the filtering will work on all versions of the page. 
- When you're ready for the custom template, replace the `template_name` in `LibraryListMini` and `LibraryListByCategoryMini` with the path to your template. Object names should be the same as in `list.html`.

Mini library views

---

requirements.in
requirements.txt

Following the dependabot notice https://github.com/cppalliance/temp-site/security/dependabot/37, I ran `just pip-compile --upgrade`. I took the opportunity to upgrade `django-test-plus` to latest `main` to be able to use latest features and fixes.

Update dependencies, including security release of requests

---

config/urls.py
news/tests/test_views.py
news/views.py
templates/news/confirm_delete.html
templates/news/detail.html
templates/news/update.html

Part of #273, rebased onto https://github.com/cppalliance/temp-site/pull/356 and https://github.com/cppalliance/temp-site/pull/370 which should land first, isolating some of the moderation logic.

Provide news entry edition and deletion.

---

.github/workflows/actions.yml

Boost generally follows a naming convention of "develop" and "master" branches. Let's switch to this.
- Create 'develop' branch as a copy of 'main'. 
- Create 'master' branch as a copy of 'main'. 
- Continue day-to-day development work in the 'develop' branch.
- Since boost.revsys.dev is a staging site it will use the code from 'develop'. 
- Every week or two, fast-forward merge 'develop' into 'master'. 
Let me know, if I should create the new git branches, or you can do that.

Organize branch names

---

core/boostrenderer.py
core/tests/test_renderer.py

Part of #394 
- Strips any tags with "footer" in them from the content that gets rendered. The data isn't meaningful -- it reflects the last time the content was converted to html, not the last time the file was actually updated. 
Before: 
After:

Strip footer from asciidoc content (Part of #394)

---

libraries/github.py
libraries/models.py
libraries/tests/test_utils.py
libraries/utils.py
libraries/views.py
templates/libraries/detail.html

Part of #252 and #394
In this PR: 
Confirmed in a live test that this passes these tests: 
- content from an adoc on `develop` (JSON library)
- content from an adoc file on a specific release (JSON library)
- content from a README for a specific release (Assign library)
- blank description when there is no readme and no adoc file (Bimap library) 
- content from a README for an older release when a newer release uses adoc (JSON older version)
Once approved, I'll rebase so the commits are pretty. 
Kicking off a task to update the description when on a non-released tag (so when on `master` or `develop`). This is different from similar logic in #394 that checks the updated date for the adoc file every time we hit the database, to see if it needs to be updated. In this case, if we are on a …

#252/#394 Render adoc content in library details page 

---

docker/Dockerfile
requirements.in
requirements.txt

Closes https://github.com/cppalliance/temp-site/security/dependabot/38 with an upgrade to `cryptography`. Also updates the `python-dev` install in the Dockerfile after I ran into an error rebuilding. I used the replacement package the error message suggested. 
Error message: 
```
#13 3.786 Package python-dev is not available, but is referred to by another package.
#13 3.786 This may mean that the package is missing, has been obsoleted, or
#13 3.786 is only available from another source
#13 3.786 However the following packages replace it:
#13 3.787   python-dev-is-python3
#13 3.787 
#13 3.789 E: Package 'python-dev' has no installation candidate
```

Upgrade crypto, change `python-dev` installation in Dockerfile 

---

templates/libraries/detail.html

Part of #252. Includes the version filter in the link to the category list page from the library detail page.

#252 Make library detail page category link version-sensitive

---

requirements.in
requirements.txt

Mainly for `cryptography` to address Vulnerable OpenSSL included in cryptography wheels

Run pip-compile upgrade

---

libraries/tests/test_views.py
libraries/views.py

@frankwiles We can probably get rid of the models and the code that populates them entirely, actually. We're only using commit data, not PR or issue data. Just wanted it to not clutter up the view anymore!

Remove open PR and Issue counts

---

libraries/models.py
libraries/tests/test_models.py
libraries/views.py
templates/libraries/detail.html

Part of #252 Making all the links on the library detail page specific to the Boost release.  
@vinniefalco Quick question -- Did you want the visible URL to just show the general link to the repo, but the actual link to go to the version'd github link? Or should the link display make it clear which version they're going to? Example: 
versus

#252 Link to versioned  library github page

---

libraries/models.py
libraries/tests/test_models.py
libraries/views.py
templates/libraries/detail.html
versions/models.py
versions/tests/test_models.py

- Adds method to the `LibraryVersion` model to generate a link to `https://www.boost.org/doc/libs/{release}/libs/{lib_path}/` (which will redirect appropriately, example: https://www.boost.org/doc/libs/1_71_0/libs/functional/factory/doc/html/index.html) 
- Tested on multiple versions of multiple libraries, including sub-libraries like "Functional/Factory" 
Part of #252

#252 Show the link to the right version of a library's docs on the detail page 

---

libraries/managers.py
libraries/models.py
libraries/tests/test_managers.py
libraries/tests/test_models.py
libraries/tests/test_views.py
libraries/views.py

Closes #252 
cc @gregnewman  -- this is the PR that will get those commit count graphs populated! 
The data comes to the template in the detail view in two variables: `commit_data_annual` and `commit_data_last_12_months`. Each field is a list of dicts, in date order: 
```
[{"date": python datetime, "commit_count": int}]
```
You can filter the `date` using the template filters to display the month and/or year as needed. **NOTE**: This data does not currently change with the version -- it's always retrieving commits to `master`. 
I didn't actually add the data to the template in this PR. 
_Edit_ Messed something up when rebasing and have to fix it.

Expose last 12 months commit counts to template

---

libraries/mixins.py
libraries/tests/test_mixins.py
libraries/views.py
templates/libraries/category_list.html
templates/libraries/detail.html
templates/libraries/flat_list.html
templates/libraries/includes/version_alert.html
templates/libraries/list.html

- Adds a mixin for the list views and includes it in the view. Detail logic is a little different. 
- Adds a template for the message 
- Includes that template in the other list templates and the detail template 
- Moves mixins to their own module 
Closes #282.
@gregnewman I did not do much with styling this so it may need your help! 
@frankwiles and @vinniefalco Right now, on the versions list page, the alert link directs to the versions page: https://www.boost.revsys.dev/versions/boost-1-82-0/. But I know we also have a "releases" mockup page: https://www.boost.revsys.dev/releases/. Which one should I link to, or should I link back to the library list page for the current version? (The detail page alert links to the current version of that specific library detail page.)

Add "older version" notice to all library list pages 

---

config/urls.py
core/managers.py
core/models.py
core/tasks.py
core/tests/test_managers.py
core/tests/test_tasks.py
core/tests/test_views.py
core/views.py

Closes #394 
- Adds model managers to delete `RenderedContent` objects by `content_type` (example: "text/asciidoc") or by `cache_key`, and clear cache by `content_type` (Clearing the cache by a key is simple enough to do directly in the task 
- Adds tasks that clear the redis and database caches via the model managers (or directly) to perform those functions 
- Adds a url route and view that allow a staff user to clear the static content cache by passing query params to a url, then passing those values async to the celery tasks 
**Note**: I didn't do any styling on this. @frankwiles I wasn't sure what you meant by "code to bust the cache" in the original ticket #394 but the bulk of the logic is in tasks anyway so this can be adjusted. 
- Log in as a staff user 
- Navigate to …

Add view to clear static content cache (redis and database) by content type or cache_key 

---

templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html

@frankwiles You were right! 
This PR fixes a bug where, when a user was on the library list page, if they selected another format to view libraries (by category, or the flat version), then selected a version or category from the drop-down, they would be shown results in the regular format. 
https://github.com/cppalliance/temp-site/assets/2286304/5f4b50f2-5402-451b-97ab-3b0d7e61adc9
https://github.com/cppalliance/temp-site/assets/2286304/85b77f0a-15f0-443b-8bce-ebdf1f3866f9

Fix libraries formatting/filtering bug

---

core/asciidoc.py
core/tasks.py
core/tests/test_asciidoc.py
core/tests/test_tasks.py
core/views.py

Closes #471 
When asciidoc content is retrieved from the database via the static content view (not the library details screen), this PR adds a refresh of that data from S3. 
- Refactored the view due to some logic shuffling for the refresh logic -- when we get the content from the db, fire the task to refresh S3. Also fire tasks as needed to save the content to the db 
- Refactors some of the asciidoc conversion code into its own `asciidoc.py` module 
- Adds celery task that takes an S3 key/content_path and a cache key, then calls S3 to re-retrieve the data with the S3 key and refreshes the data in `RenderedContent` using the cache key. 
- Adds celery task that handles the actual saving of the content

471 refresh

---

libraries/mixins.py
libraries/views.py

Closes #278 by making the category drop-down include only categories that appear in the selected version's libraries. 
Refactored out the mixin as it wasn't needed anymore.

Make categories in drop-down version-sensitive

---

config/settings.py
templates/account/password_reset_done.html
templates/account/password_reset_from_key.html
templates/account/password_reset_from_key_done.html

@gregnewman I tested the password reset flow in staging and it works, so I think you were right that it was the email not being set up. 
I found the relevant templates for the process and did the initial override to use our base template, so once this is merged, it's ready for the real design! (The text in the screenshots is huge because I bump up my font size 👓  ) 
Result:

Override password reset templates 

---

templates/socialaccount/signup.html

Overrides the screen that asks to confirm your email after you sign up

Override django-allauth social signup template

---

templates/versions/detail.html
versions/tests/test_views.py
versions/views.py

Closes #492 
- Makes the release selection form on the releases page work, so the drop-down menu can be used to navigate to other releases

492-see-old-releases

---

core/views.py
docs/development_setup_notes.md
templates/socialaccount/authentication_error.html
templates/socialaccount/login_cancelled.html

- Fixes #403 "page not found" error when user cancels a GitHub signup. 
- Also documents local dev setup for django-allauth. 
This was a weird one. When a user starts the process to sign up with GitHub, but cancels their registration on the screen where GitHub asks them for authorization, then the user would be redirected to a "page not found" screen. I figured out that the callback request when the user cancelled was being routed through the StaticContentView; I'm not sure why. I added some code to that view to catch these cases. 
Result:

Fix 404 error when user cancels a GitHub signup 

---

kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

@frankwiles, Copying MAILGUN_API_KEY to the other values.yaml files. Future changes in kube, or github actions, could be done in all the values.yaml / actions.yml files so they propagate to all environments. (Or, chat about it).

MAILGUN_API_KEY in values.yaml files

---

stage_static_config.json
templates/versions/detail.html
versions/models.py
versions/tests/test_models.py

Closes #499
In this PR: 
- New method in Version model for generating a link to older release's docs 
- Adds the docs `site_path` to the S3 static content map, so the URL generated in the Version method points to S3 
- Updates the template 
Result:

Add live docs link to Releases page 

---

kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

Add a GITHUB_TOKEN variable in the kube files.
Depends on a secret "githubtoken" existing in the namespace. _Create the secret before merging the PR._ I've added it to the other namespaces already. Any github user token will work as long as it authenticates the user and thus allows a higher api rate limit. We have a cppalliance-bot account for CI and use that token.

GITHUB_TOKEN variable in kube

---

templates/versions/detail.html
versions/views.py

Part of #524 
> After running import_versions, go to /releases/ page, select another version (let's say 1.75.0) in the drop-down, then it shows in the drop-down (Newest Version (1.75.0), which is wrong, because 1.75.0 is not the newest version. 
This PR addresses that bug.

Correct the "Newest Release" message in the drop-down

---

docs/commands.md
libraries/github.py
libraries/management/commands/import_library_versions.py
versions/management/commands/import_versions.py

Part of #524  
- `import_library_versions`: "This crashes at hana in boost version 1.65.0. See note 2 below." -- I am not sure why, but for the Hana library for version 1.65.0, the `submodule` field from the `.gitmodules` entry for that library does not work to retrieve the repo data, but using the `url` field from the `.gitmodules` file does. There aren't obvious differences for `hana` for 1.65.0 vs other versions, that I can see. I caught the error and changed the command to try again with the other field, then edited the script to more gracefully handle it when data isn't found. 
- As part of debugging this, I realized there is an error with 1.61.0, where its `.gitmodules` file can't be accessed at all. That failure is now handled gracefully, but needs to be debugged more fully. 
- …

Fix bugs in the library, version, and library-version load scripts 

---

stage_static_config.json

Moves the `/doc/` site_path lower down to allow more specific/more accurate paths to show up first in the list of s3 keys. 
@nessita As far as I can tell, this change retains the fix I made for https://github.com/cppalliance/temp-site/issues/255 but should address the issue we discussed where less-specific (and therefore bad) paths were showing up first! 
Example with new order: 
```
In [1]: key='/doc/libs/boost_1_48_0/doc/html/accumulators/acknowledgements.html'
In [2]: from core.boostrenderer import get_s3_keys
In [3]: get_s3_keys(key)
Out[3]: 
['/archives/boost_1_48_0/doc/html/accumulators/acknowledgements.html',
'/site-docs/develop/libs/boost_1_48_0/site-docs/develop/html/accumulators/acknowledgements.html',
'/site/develop/doc/libs/boost_1_48_0/doc/html/accumulators/acknowledgements.ht …
```

Move /doc/ site_path lower down

---

docs/commands.md
libraries/github.py
libraries/management/commands/update_libraries.py

Run `./manage.py update_libraries --local` to skip the most time-consuming github data for local dev. Now the command takes a minute or two to run and doesn't rate limit. Will be missing the release date for the library and the monthly commit history. 
FYI @gregnewman @nessita @frankwiles @4down @sdarwin

Skip time-consuming github data for local dev

---

config/urls.py
templates/users/profile_base_new.html
templates/users/profile_new.html
users/tests/test_views.py
users/views.py

Adds a new profile update page that puts all forms on a single page per Friday's meeting. 
- Update password (will log you out and force you to log back in with new credentials) 
- Import GH photo (synchronous for now -- there is a bug when it's call async that I'll address in a separate PR) 
- Upload new photo 
- Manage notification preferences 
- Each form submits on its own -- so if I select a new photo to upload AND change my notification preferences, then if I hit the "upload new photo" button, my new preferences **will not** be saved, and vice versa. I can change this, but I didn't want to get too ahead of myself before design had been discussed, so I kept them separate for now. 
in a new URL `/users/me/new/` to retain existing functionality (just in case).

New single-page profile page: Change password form

---

config/urls.py
core/boostrenderer.py
core/htmlhelper.py
core/tests/fixtures.py
core/tests/test_htmlhelper.py
core/tests/test_renderer.py
core/tests/test_views.py
core/views.py
stage_static_config.json
templates/base.html
templates/docs_libs_placeholder.html

This modernization occurs on the fly over potentially-cached S3 files. This
means, the legacy doc pages are fetched and cached just like any other S3
static content, and the modernization happens when the page is requested.
This way, we can safely render modern parts of the pages (like the header)
and account for dynamic state such as logged in users.
The resulting docs (also called FrankenDocs :-)) are processed using
BeautifulSoup and a fairly simple heuristic that can be found in the
`core/htmlhelper.py` module.
Fixes #534.

Modernize legacy doc libs pages fetched directly from S3.

---

static/css/styles.css
templates/versions/detail.html

On mobile devices 10 chars
On medium browsers 20 chars
On x-large browser show the whole hash

Truncate hashes

---

templates/libraries/_library_list_item.html

On the library list page, when you select an older version, the links for the libraries don't link to the older version of that library.  https://www.boost.revsys.dev/libraries/?q=&category=&version=boost-1-79-0

Fix library detail url for older versions

---

config/settings.py

Added `MAX_CONNECTIONS` environment variable and set it to default to 20 as a reasonable default.
Fixes #590

Reduce max database connections

---

templates/account/login.html

Part of #570 
- Displays non-field errors in the email login form 
@gregnewman There is still an issue -- the error shows in the email form, which is hidden when the page reloads when the user's password is wrong. Is this better solved on the JS side of things? 
https://github.com/cppalliance/temp-site/assets/2286304/35e4f375-6288-4ab0-bc01-e54d3c94e9ef

#570 Show non-field errors on email login form

---

templates/account/password_reset_from_key_done.html

For convenience, adds a link to the login page when a user successfully changes their password.

Add link to log back in after changing password

---

templates/socialaccount/signup.html

When a user registers with a social account that has an email that already exists in the system, add a link to log in to the site for convenience

Add link to login when user registers with duplicate email

---

ak/tests/test_default_pages.py
ak/views.py
news/models.py
news/tests/test_models.py
templates/homepage.html
templates/homepage_beta.html

Closes #519 
- Add a `published()` method on the Entry manager 
- Return the most recent 3 news articles on the main homepage and most recent 2 on the beta homepage, as I wasn't sure which one we were using 
- Updated both homepage templates 
- Updated tests

#512 Add last 2 published entries to the homepage context

---

templates/includes/_header.html

Have the `Boost_Brandmark_BlackBoost_Transparent.svg` image use a relative path instead of absolute. 
The issue with an absolute path containing "request.scheme" is that Django thinks the request scheme is http when it's really behind a load balancer in production, serving the page with https.  In Firefox, an https page with http images generates a browser error.

Brandmark link uses relative path

---

libraries/management/commands/import_library_versions.py

closes #616 
The problem was that when `import_library_versions` runs and loads the maintainers, it only tries to load them if the `LibraryVersion` was created. Since older versions of WinAPI had maintainers, and my local db had maintainers for the current version, it looks like the LibraryVersion for WinAPI-1.82.0 was probably created, but for whatever reasons its maintainers didn't load. And on subsequent runs of this import, the maintainers wouldn't be attempted since the LibraryVersion record already existed. 
I changed the logic to try and import maintainers if there aren't any, regardless of whether the LibraryVersion record is new. 
Once this is merged, `./manage.py import_library_versions --min-release=1.82` will need to be run in deployed environments.

Import maintainers when there are no maintainers

---

config/settings.py
docs/commands.md
libraries/management/commands/import_library_version_docs_urls.py
libraries/management/commands/import_library_versions.py
versions/management/commands/import_versions.py

Per our meeting on 9/1, this PR sets the oldest Boost version to import to the oldest we have docs for in S3. The oldest we store is 1.31.0 -- see screenshot.

Add setting for minimum Boost version to import

---

config/urls.py
core/views.py

* Adds viewset to inject the header into the user-guide
* Removes old antora header views and urls

:sparkles: inject header into user guide

---

config/urls.py
libraries/tests/test_views.py
libraries/views.py
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/list.html

- Removes the `by_category` from library list templates and from the view 
- Removes the library list mini category template, view, and url route; no longer used

Remove unused url, unused template logic

---

.github/workflows/actions-gcp.yaml
kube/boost/templates/celery.yaml
kube/boost/templates/deployment.yaml
kube/boost/templates/service.yaml

If the commit SHA is used as an ImageTag and happens to be numeric, helm interprets that is a number instead of a string.  To solve the issue quote the "ImageTag" value.

Quote helm ImageTag to force string type

---

static/css/styles.css
templates/docs_temp.html
templates/homepage.html
templates/libraries/_library_list_item.html
templates/news/detail.html

- Homepage
- Moved download button to the right of the opening text.  
- Cleaned up display when going to mobile for hero section.
- Homepage Calendar
- Hardcoded calendar items for Oct, Nov, Dec until we have built integration with Google Calendar
- Learn top margin/padding
- Lozenge text update
- Testing of News External URL (don't have data locally)
resolves #655, resolves #656 (potentially, will open new issue if needed), resolves #573, resolves #568

Homepage Download + Calendar Hardcode, Misc Fixes

---

kube/boost/templates/configmap-nginx.yaml
kube/boost/templates/ingress.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

A new domain preview.boost.org is being added. 
DNS updates are pending. 
Most of the web changes, although not all, can be made in advance by adding a `fqdn3` to the kube files as a placeholder.

Add fqdn3, new preview DNS domain

---

kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

MAILGUN_API_KEY depends on MAILGUN_SENDER_DOMAIN, so adding that now.
Eventually the domain should be switched to a "boost.org" domain, but that can be done later when the domains names have stabilized.

MAILGUN_SENDER_DOMAIN variable

---

config/urls.py
users/views.py

Note to self: see the `#TODO` comments for what to finish in the morning. 
✅ A new user with a new email address: registers fine 
✅ Password mismatch: shows error 
✅ Invalid email: shows error 
❓ What would happen if one of these people just went straight to the Forgot Password and didn’t attempt to sign up?  Would it work, or would it fail because the account hasn’t been claimed?  _Exopected behavior: it works, and the account is marked as claimed. Need to test._ 
✅ Existing user who is `claimed`, meaning they interacted with their account in some way: shows the expected error that an account already exists, but doesn't send the password reset email 
✅ Existing user who is not `claimed`, meaning they were imported as a maintainer or author: receives a password reset email, is shown a …

[WIP but ready for review] Allow maintainers and authors to claim their User accounts by resetting their passwords 

---

config/settings.py

Part of #667. Updates `DEFAULT_FROM_EMAIL = "info@cppalliance.org"` and `SERVER_EMAIL = "errors@cppalliance.org"`

Change DEFAULT_FROM_EMAIL and SERVER_EMAIL

---

users/models.py

The original code incorrectly assumed that the User object would always have a first and last name and that they would be unique across users.
This changes the filename to be "profile-{user.pk}-{10 random characters}.png" which should ensure there is no overwritting happening.
Fixes #543

Github profile image save bug

---

config/urls.py
users/tests/test_views.py
users/views.py

Part of #667 
Commented out the test -- it passes, but some `breakpoint()` indicate that it isn't actually testing anything. I did a live test, though, and was able to: 
- Have a user who is not `claimed` with the same email address as my gmail account
- Try to connect as a new user via that gmail account 
- See a message that there is an account for me already 
- Get an email with the reset password link, reset the password, log in, then connect my Gmail account from my profile 
- Sign out, then sign in with email address and password 
- Sign out, then sign in with gmail 
- Confirm in the admin that the accounts are linked appropriately 
How to test: 
- Log into the admin with your admin account and create a new User.
- Enter the email and password x2. Select “save and continue editing.” …

Allow user to claim account via social auth/password reset when trying to connect

---

config/settings.py
docs/README.md
docs/unclaimed_user_accounts.md
users/forms.py
users/models.py
users/tests/test_forms.py
users/tests/test_models.py
users/tests/test_views.py
users/views.py

Closes #667 
- Adds a method to claim users 
- Uses that method when a user resets their password from key (from the password reset email) 
- Uses that method when a user resets their password from the profile page 
- Adds docs about unclaimed users, where they come from, and how we handle them

Flip claimed switch to true when user resets password via key or profile 

---

static/css/styles.css
templates/socialaccount/signup.html

Adds a muted red background to the errors with white text.
Issue: #599

:art: styles errors on account signup

---

docs/README.md
docs/dependencies.md
libraries/tests/test_views.py
libraries/views.py
requirements.txt
versions/managers.py
versions/models.py
versions/tests/fixtures.py
versions/tests/test_managers.py
versions/tests/test_models.py
versions/views.py

Closes #711 
- Adds new manager method for version dropdown 
- Adds logic to that manager method to exclude beta versions that are older than the most recent full version or for the most recent full version 
- Change the versions being returned in the views for the library and releases pages 
- Adds docs for dependency management / update requirements. (I wound up removing an external package I was going to use, but I'd already updated with `pip-compile` so it seems harmless to include the update since it's mostly comments)

Only show beta releases in drop-downs if they are for versions newer than the most recent version

---

libraries/mixins.py
libraries/tests/test_views.py
libraries/views.py
templates/homepage.html
templates/libraries/list.html
templates/versions/detail.html
versions/tests/test_views.py
versions/views.py

Closes #700 
- Hides rest of template for releases page and libraries list page when there is no data 
- Adds message that there is no data that is appropriate for prod but lets a local developer know what the issue is 
- Hides "featured library" block when there is no featured library

Add better messaging, more graceful handling when no data has been imported 

---

ak/views.py
config/urls.py
core/tests/test_views.py
core/views.py

Part of #724, closes to #175 
- Corrects an issue where a 404 status code was being returned in a convoluted way 
- Enforces our 404 template as the one to use any time a 404 is raised 
- Fixes some tests

Fix our custom 404 page 

---

config/settings.py
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

Don't merge without creating a k8s secret, I will send the file.
This pull request adds Django variables pointing to mailman3 servers.
Main tasks to include mailman3 in the project:
- Install mailman3-core servers on dedicated VMs in Google Cloud.  They are running. There is a mailman core instance for each environment (stage, production, revsys).  Separate database, different from Django.
- Add mailman3-web front-end to the Django project. Use the same set of user accounts, passwords, database, etc. This front-end web integration still remains to be done, Nessita was working on that.
What's provided here are secrets and variables allowing web to reach mailman-core. If you would like to ssh into the servers we can set up access.

Mailman variables

---

README.md
docs/dependencies.md
requirements.in
requirements.txt

- Adds elasticsearch with necessary version into requirements.in and requirements.txt
- Updated the dependency management doc to use `docker compose up` for the final command since `just up` is not valid
- Updated root README to include section to direct people to the dependency management doc
Resolves #746

Dependency for elasticsearch + Updates to docs

---

stage_static_config.json

Added the mapping of /page to s3:/site-pages/ as discussed in #724.
None of the existing mappings were removed.

Added /page mapping to root of site-pages

---

kube/boost/templates/deployment.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

Set the memory, cpu, and storage on the django pod.  Currently setting all environments to a low number (1 CPU) , this can be modified at any time, especially when the number of users is likely to increase.

Set CPU on deployment

---

static/css/styles.css
templates/account/login.html
templates/account/signup.html
templates/base.html
templates/community_temp.html
templates/docs_temp.html
templates/homepage.html
templates/includes/_header.html
templates/libraries/category_list.html
templates/libraries/detail.html

resolves #763 
resolves #742 
- removed remaining Slack links
- removed placeholder text from login/sign up forms (still to do on profile update)
- created the docs menu in header as discussed in last meeting
- likewise added links to all 3 into the mobile menu
- community page updates based on adobe express feedback - this is a step towards getting the page to a much better state, some items are removed at the moment and issues will be created shortly for bringing those back with more content. 
Lot of style changes in preparation for completing style guide .  Many more to come.
- padding made consistent where it was not before in the panels across homepage, learn, and community
- headers made consistent for panel headers 
- learn page styles toned down and now match the other sections

Slack out, many style updates

---

users/forms.py
users/tests/test_forms.py

Resolves #804 
- Overrides form `save()` to manually delete the old image before saving the new one

Delete old image file when user uploads new image

---

templates/libraries/includes/version_alert.html
versions/admin.py
versions/tasks.py

Part of #386. 
- Adjusts the github call to get the gitmodules file to be more flexible and retrieve for tags and branches 
- Adds import of development versions to the admin button that imports new version data 
- Adjusts the outdated version notice to accommodate development branches

Adds ability to get library-versions for `master` and `develop` branches via the admin 

---

news/tests/fixtures.py
news/tests/test_views.py
news/views.py

Closes #793 
- Adds check that user has a profile photo before letting them access the page where they can choose news to post
- If they fail the check, show a message and redirect to the profile screen. 
Example of result: 
https://github.com/cppalliance/temp-site/assets/2286304/17d8a23a-fa98-461f-ab72-7ff8f9d7d081

Require profile photo before users can post news

---

kube/boost/templates/gateway.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

The next generation Ingress is 'Gateway API'.  
It's necessary to switch to Gateway because that is compatible with Certificate Manager in GCP, which in turn is needed to allow 'DNS authorization' type certificates.

K8S Gateway API replaces Ingress

---

core/admin.py
templates/versions/detail.html
versions/models.py
versions/releases.py
versions/tasks.py
versions/tests/test_models.py
versions/views.py

Part of #617 
- Adds admin for `RenderedContent` model 
- Adds release notes to the release notes detail page view and template 
- Adds a property to the version model with the release notes cache key, to make it easier to get the release notes for that version 
- Adds functions to get the release notes html from the repo, do some basic stripping of it, and saving it to the RenderedContent model 
- Hooks those functions up to a celery task, and add that celery task to the admin button that downloads new versions 
In a future PR: 
- More HTML massaging to remove some of the duplicated markup 
To use this feature: 
- Click the "import new releases" button again, but be aware that the output isn't yet pretty, so I wouldn't recommend it yet

Download release notes HTML for past releases 

---

core/htmlhelper.py
core/tests/test_htmlhelper.py
versions/releases.py

Closes #617 
- Adds helper functions to clean up the release notes html. These functions remove duplicate headings, remove excess empty div tags, flatten nested lists, remove UI elements and classes no longer needed, hid the download tables, replaced the links with local ones, etc. 
- Adds that process to the release import process via the admin 
Screenshot of UI:

Modernize release notes 

---

config/settings.py
core/context_processors.py
core/tests/test_context_processors.py
news/tests/test_views.py
templates/includes/_header.html
versions/models.py
versions/tests/test_models.py

Closes #844 
- Adds a context processor to add the current release to the context on all pages 
- Adds a `cached_property` to the `Version` model that formats the slug the way we need it 
- Makes the inclusion of the data conditional on having a most recent release, so the site doesn't have a problem if data hasn't been imported
- Fix some tests
Local demo:

Make current-boost-version dynamic for boost-gecko in site header

---

templates/news/list.html

None of the CSS seems to be getting picked up on the news listing page, testing with a small change.

Margin-left on news listing

---

news/notifications.py
news/tests/fixtures.py
news/tests/test_notifications.py

closes #772  
- uses `mark_safe` in the notifications templates in the `news` app 
- updates fixtures and tests

Mark special chars safe in emails

---

docs/hosting/README.md
docs/mailman/README.md

The current boost.org website stores internal administrative documentation in multiple locations including https://github.com/boostorg/wiki/wiki and https://github.com/boostorg/boost-tasks. When considering the topics of AWS S3, server instances, the CDN, clusters, etc. most end-users and boost developers do not need this information.  If the documentation were included in a folder of the temp-site repo, it would consume storage and slow down web deployments. So a proposal is to have a separate docs repo, https://github.com/cppalliance/temp-site-documentation  .

Website hosting docs

---

templates/versions/detail.html

Part of #386 
Release notes only apply to full releases, so this PR hides that URL when the release object is not a full release.

Hide release notes url when not a full release

---

versions/managers.py
versions/tests/test_managers.py
versions/views.py

Closes #863  
- Adds a stricter version of the manager method with the versions drop-down that excludes development branches 
- Use that version in the versions context

863 dropdowns

---

kube/boost/templates/gateway.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

In the k8s Gateway API use a static rather than an ephemeral IP address, with the NamedAddress setting.

Gateway IP NamedAddress

---

kube/boost/templates/gateway.yaml
kube/boost/templates/ingress.yaml
kube/boost/templates/service-gateway.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

Ingress and Gateway both place annotations on a service. To be able to activate those at the same time, and avoid conflicting annotations, create another service object in parallel.   
The reason for this is to add another domain name (as seen in the pull request) without disrupting the existing domain preview.boost.org.

k8s: enable simultaneous Ingress/Gateway

---

config/urls.py
docs/README.md
docs/rss_feeds.md
templates/versions/detail.html
versions/feeds.py
versions/models.py
versions/tests/test_feeds.py
versions/tests/test_models.py

Part of #339  
- Adds RSS and Atom feeds, using the existing pattern `/feed/downloads.rss` 
- Fields are the same as https://www.boost.org/feed/downloads.rss
- ~having trouble getting pub_date to render even though the test passes so I will look at that next week~ Publishing the Atom version took care of that

Add Releases RSS feed 

---

config/urls.py
news/feeds.py
news/tests/test_feeds.py
templates/news/list.html

Closes #339 
- Adds `/feed/news.rss` and `/feed/news.atom` 
- Includes the same fields as the original: https://www.boost.org/feed/news.rss 
- Adds a link to the News listing page 
- News RSS feed includes all published `Entry` types but we can exclude some news types if desired.

Add News RSS and Atom feeds

---

kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

I've created an API key in https://console.cloud.google.com/apis/credentials?referrer=search&project=boostorg-project1 named `calendar_api_key` and will send this to Lacey and Spencer.   Also it's a django env variable CALENDAR_API_KEY.  
Any key allows read access to a public calendar, even without permissions, and that's how this is working.
The boost calendar can be embedded in the website:  
```
<div class="section-body">
<p>Below is a community maintained calendar of Boost related
events. The release managers try to keep the release related
portion of the calendar up to date.</p><iframe src=
"https://www.google.com/calendar/embed?src=5rorfm42nvmpt77ac0vult9iig%40group.calendar.google.com&amp;ctz=America/Chicago"
class="c1" width="100%" height="600" frameborder="0" scrolling= …
```

Calendar API key

---

ak/views.py
config/settings.py
config/urls.py
core/calendar.py
core/tests/test_calendar.py
core/tests/test_views.py
core/views.py
docs/env_vars.md
env.template
templates/calendar.html
templates/homepage.html

Part of #760 
- Adds functions to retrieve raw events from the Google Calendar API, extract the data we need for those events, and order those events by month for display 
- Documents the new env vars 
- Adds new setting for the google calendar API url 
- Adds `/calendar/` to URLs, which displays the rendered google calendar **but didn't prettify it**
- Adds events to homepage, using the existing template 
- Edits to the homepage template to show the events and make the paging arrows work
Per the ticket, 1 and 2 are done with this PR: 
> 1. On the homepage in succinct line item form
> a. Using the same layout/functionality as the hardcoded "Schedule of Events" section currently on the new homepage or
> b. If there is a suggestion or idea for something that might work better, we should …

Pull in data from community-maintained events calendar 

---

ak/views.py
config/settings.py
docs/README.md
docs/calendar.md
docs/env_vars.md

Part of #760 
Adds caching for google events calendar, adds docs about how those events are retrieved

Add event caching, add event docs

---

config/settings.py
docs/env_vars.md
docs/release_downloads.md
versions/management/commands/import_artifactory_release_data.py
versions/releases.py
versions/tests/test_releases.py

Part of #878  
New link: `[boost_1_83_0.tar.gz](https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz)` 
Admin screenshot:

Remove extra slash from artifactory download links 

---

news/tests/test_views.py
news/views.py

Closes #806 
- Requires first or last name to post news 
- Changes the error message the user sees to account for their potential missing name 
- Adds tests 
- Adds back in `news/` views tests, but skips the ones that failed for me locally and failed in CI  
FYI @4down @gregnewman This adds back in the `news/` app tests, but skips the ones that fail locally and in CI. Let me know if you have issues locally and I can skip more of them.

Require users to have a first or last name, in addition to a profile photo, to post News items

---

package.json

- tailwindcss pinned to 3.2.1
- @tailwindcss/forms pinned to 0.5.3
Default behavior when adding a package using npm results in the version syntax in package.json where it uses the caret, which keeps the versions in the same major release but easily leads to different versions existing on different envs.  
Using ie. `npm i tailwindcss@3.2.1 --save --save-exact` keeps the package at an exact version.

package.json updated for exact versions of tw/forms and tw

---

core/templatetags/text_helpers.py
static/css/styles.css
templates/homepage.html
templates/news/list.html

- resolves #893 
- resolves #837 
Adds filter multi_truncate_middle to update exceptionally-long strings inside of news text to have a "..." in the middle of the string.  
Modified layout and styles on the homepage news listing, brought over styles from the news listing and added a slight indent / added author image next to title to try to make the section look better as a standalone section.
Will need to fine-tune the argument passed which sets the length a string needs to be for this to kick in after seeing it in action with more actual data most likely.  Possible issue which will get created shortly - what about long URLs, how is the behavior working currently - it could result in a broken link since URLs have the `<a>` tag added.  Noting so I don't forget.

Truncate latest + homepage and news list

---

config/urls.py
core/boostrenderer.py
core/tasks.py
core/tests/test_renderer.py
core/views.py
docs/static_content.md
libraries/tests/test_tasks.py

Closes #886 
- A new URL route for images from S3: `/images/`. This route will allow us to access images directly from S3 while still masking the S3 key. Example URL: `http://localhost:8000/images/site-pages/develop/url-style-guide-image.png` 
- Converted the existing `StaticContentView` into a base class, so I could add extra processing to the HTML produced by the static content without affecting the other views (like the library docs view) that inherit from the `StaticContentView`. The library docs, for example, have their own HTML processing that was easily disrupted and not easily debugged. 
- The new `StaticContentView` now inherits from the `BaseStaticContentView`, and does its own processing to replace the image URLs with fully-qualified paths to the `/images/` view (and thus, …

Replace relative image URLs with fully-qualified paths for static content

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

- Refactor to allow for multiple documentation paths for a single library
- Add more helper functions
Also did a live test
Part of #900 
See gist: https://gist.github.com/williln/3a21931bb050e3394fb7a581eb792734
> IO -
> Boost Versions 1.64.0 through 1.72.0 the docs are here:
> https://www.boost.org/doc/libs/1_72_0/libs/io/doc/index.html
> Boost Versions 1.73.0 -> present
> https://www.boost.org/doc/libs/1_73_0/libs/io/doc/html/io.html
This PR takes care of that comment.

Fix documentation urls for IO library

---

libraries/github.py
versions/tasks.py

Part of #900 
See gist: https://gist.github.com/williln/3a21931bb050e3394fb7a581eb792734#gistcomment-4877288 
> Chrono.Stopwatch -
> Importantly, it does not appear in .gitmodules.
> List of libraries page (preview): Does not appear
> List of libraries page (existing site): Does not appear
> There were some quickbook docs in the git repo boostorg/chrono/ ... /doc/stopwatches however they were not compiled or published.
> "Versions affected: 1.68.0 back to 1.63.0". If those versions completely ignored Boost.Stopwatch by not publishing docs
or linking to Boost.Stopwatch on the boost website then the same thing could be done now. Remove Boost.Stopwatch. Its source code will still be present in an archive download.
This PR addresses this comment

Add logic to exclude chrono/stopwatch from libraries

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py

Part of #900 
See gist: https://gist.github.com/williln/3a21931bb050e3394fb7a581eb792734 
> StringRef -
> Boost Version <= 1.77.0 the docs are here:
> https://www.boost.org/doc/libs/1_77_0/libs/utility/doc/html/string_ref.html
This does not address the StringRef docs for 1.78.0 and higher, or that it was renamed StringView.

900 string ref

---

libraries/tasks.py
libraries/tests/test_utils.py
libraries/utils.py
versions/tasks.py

Part of #900 
See gist https://gist.github.com/williln/3a21931bb050e3394fb7a581eb792734 
> Boost Version >= 1.78.0 the docs are here:
> https://www.boost.org/doc/libs/1_84_0/libs/utility/doc/html/utility/utilities/string_view.html
> Remove String Ref in boost >= 1.78.0 since it has been renamed string_view.

Add exception logic for String View docs 

---

libraries/tasks.py

Part of #900 
All of these libraries used the same link format, which is why they are in the same PR. 
- Circular Buffer
- Date Time
- Interprocess
- Intrusive
- Program Options 
- String Algo

Add exception logic for more libraries' docs links

---

config/urls.py
core/views.py
static/css/styles.css
templates/includes/_footer.html

Did this through Django, though it might be better to handle direct links to text files from the web server - likely not a major concern.   Will note on the issue.
- Added route to /LICENSE_1.0.txt
- Added Distributed under the Boost Software License, Version 1.0 text to footer with link to this route
resolves #978 
resolves #968

BSL License file route + text in footer

---

libraries/constants.py
versions/tasks.py

Part of #900 
Adds logic to skip some specific library-versions in the load script. 
_note_ These will need to be manually deleted from the DB (via the admin) but they won't load again after that.

Add logic to skip loading some library-versions

---

.gitignore
config/settings.py
libraries/tasks.py

Part of #900 
Corrects the missing_docs logic for the versions older than 1.30.2, which don't have docs in S3. Also adds a setting to update the newest version with missing docs, in case what is stored in S3 changes later. 
Updates the minimum Boost version, to reflect what's in Prod anyway.

Fix logic that marks older versions as missing docs

---

kube/boost/templates/configmap-nginx.yaml

fixes #743
This was broken: 
https://www.boost.io/doc/libs/1_83_0/libs/json
While this works ok:
https://www.boost.io/doc/libs/1_83_0/libs/json/
A default nginx vhost tries URIs in order. How can that be done with proxy_pass.
```
location / {
try_files $uri $uri/ =404;
}
```
1. Using the nginx "try_files" directive, sends all requests to a named location `@django1`.
2. `@django1` tries to serve the file. If it hits a 404 error, sends the request to `@django2`.
3. `@django2` adds a trailing slash (if one is missing), and sends back a redirect to the browser. 
4. The client request the file again, this time with the trailing slash. It loads. 
In some ways, it would be nice to use an internal rewrite, and instantly return a result, instead of a multistep process where `@django2` returns a …

Nginx try_files, includes trailing slash

---

templates/includes/_footer.html

Added "Proposed for boost.org" in the footer as per #993

"Proposed for boost.org" added to footer.

---

templates/libraries/detail.html

This pull request fixes links to categories from the library detail page.

Fix category URL in library detail page

---

config/urls.py

This change makes links in /releases/ clickable.

Add redirect for '/libs/' legacy boost.org urls in config/urls.py

---

core/views.py

This pull request enables the theme switcher to be visible on documentation pages.

Show theme switcher on docs pages

---

templates/versions/detail.html

Fixes #908. This removes the link to release notes on the release notes page. 
Added some horizontal whitespace above the two remaining divs in that section, to improve spacing with the new missing div.

Remove unnecessary Release Notes link from top section

---

config/settings.py
docs/commands.md
docs/env_vars.md
requirements.in
requirements.txt
versions/management/commands/import_archives_release_data.py
versions/releases.py
versions/tasks.py
versions/tests/test_releases.py

This pull request adds support for `archives.boost.io` to the codebase, while leaving intact the artifactory code. 
Resolves #1005.

Replace Artifactory URLs with `archives.boost.io` URLs

---

news/feeds.py

If a news item lacks a content body, but includes an external link, the description for that RSS item is now:
```python
f"External link to <a href='{item.external_url}'>{item.external_url}</a>."
```
This should resolve #946.

Add support for external URLs in item description for RSS feeds

---

libraries/tasks.py
libraries/tests/test_tasks.py
libraries/views.py
versions/models.py
versions/tests/test_models.py

This pull request seeks to solve #728.
With this change, libraries and documentation are using the `/1_83_0/` url format instead of `/boost_1_83_0/`.

Fixes #728

---

core/htmlhelper.py
core/views.py

This pull request seeks to fix #621.
Basically, "modernization" of the doc is disabled if the request is coming from an iframe. Here's a pic of a currently–affected library's docs now:
We'll want to find a way to include our header here, eventually, but this is a good solution for restoring the functionality of these pages.

disable modernization for iframe requests

---

libraries/views.py
versions/views.py

This may not be the approach we want to take, but here's a pull request that aims to solve #1040 using Django sessions.

Use Django Session to intelligently remember which boost version was explicitly selected

---

libraries/models.py
templates/libraries/detail.html

Solves #1043. This adds `Library.display_name` and `Library.display_name_short`, which reflects the rules outlined in issue #1043.
There are a few instances where we will need to update the library name in Django Admin, I believe (e.g. `Boost.StlInterfaces`).

Fix library display names

---

core/boostrenderer.py
stage_static_config.json

See issue 724.  Remove static content requests from "/" that don't match any specific mappings.
```
{
"site_path": "/",
"s3_path": "/site/develop/"
}
```
This s3 path  "/site/develop/" does not even exist in S3.   
If a bot requested a page `/not-a-file` it would generate a request to S3 every time.  
Before this modification a missing page 404 took 800ms or 1sec.     Now it might be 200ms which is 4-5 times faster.
Before, Cloud Logging showed many "get_content_from_s3_error" errors.   Now those errors are gone.

Remove fallback url map going to s3

---

templates/libraries/detail.html

This PR allows avatars to be a fixed height and its image to cover its parent no matter what the aspect ratio is
Solves: #1044

Fix maintainers avatar photo aspect ratio #1044

---

docstailwind.config.js
frontend/docsstyles.css
frontend/styles.css
frontend/userguidestyles.css
static/css/styles.css
tailwind.config.js
templates/base.html
templates/includes/_header.html
userguidetailwind.config.js

This PR removes the Cairo font family and sets a modern fallback sans-serif font stack
This addresses #1065

Remove Cairo font family reference globally

---

frontend/styles.css
static/css/styles.css

This PR allows links, or anchor tags, to resemble a standard blue link when rendered. Fixes #939 
- In the Build Status section: are we ok with the "master", "develop" losing their background-color?

Make links inside library or releases to standard blue

---

libraries/views.py

This code fixes a bug related to #1061.

Fix setting selected boost version in LibraryList view

---

libraries/views.py

The releases and libraries pages have boost version drop-down lists. We have implemented functionality to save the version as a session variable, also using a cookie.  I found one more case. The Library Details page. This pull request remembers the boost version if you select it on that page. Otherwise, all the hyperlinks going to those pages already include a version in the URL, so that aspect doesn't need to be adjusted. What's added is to store/remember a version, if modified.

Set boost version session variable from library detail page.

---

templates/community_temp.html

This PR adds the discussion policy link to the Mailing List tab. Also removes the bold heading for Cpplang Slack Workspace for visual consistency.
Fixes #1087

Add discussion policy link to community page

---

templates/includes/_header.html

Removes unnecessary `h-full` class from mobile header logo container, preventing an oversized nav on library doc pages in mobile view. 
Fixes #1107

Fix mobile header height

---

core/htmlhelper.py

Solves #1116
The code changes in `htmlhelper.py` remove the sponsorship links about downloads from the release notes. This improves the clarity and focus of the release notes by removing unnecessary information.

Remove sponsorship links about downloads from release notes

---

templates/community_temp.html
templates/docs_temp.html

border bottom lines were spaced too close to the text. Added a bit more space.

fixed border bottom spacing on learn and community pages

---

templates/includes/_header.html

Allows nave to scroll across site. overlaps in antora docs, but that will be fixed in the antora dark theme ui branch.

allow nav to scroll

---

frontend/styles.css
tailwind.config.js
templates/includes/_header.html

from the ticket:
Replace boost logo in nav bar with "B" icon. - completed
change nav bar bottom border to give depth - completed
in dark theme, change body text color to #e6e6e6 - added offwhite color to root color vars,and included in dark body, but there needs to be extensive work done with the classes and pulling out unneeded tailwind commands.
Additionally, included https://github.com/boostorg/website-v2/issues/1152 into this as well.

header and site colors update

---

README.md
docs/development_setup_notes.md
env.template

Testing docker-compose. Here are things I noticed.  
- `styles.css` seemed to be missing in the local docker-compose environment, even though it's present in the docker image.  With docker-compose a volume is mounted.  The volume points to your git repository where styles.css is now git-ignored.   
Therefore, I am adding steps in the README to build `styles.css`.   @kennethreitz @rbbeeston , is this incorrect?  Should the instructions be different?  What method do you use?
- local development: there had been a note to install Python 3.11.   Even though Django containers are running with Python 3.11, it should be acceptable for the local OS to have the system default of Python 3.10.   They are not directly interacting.   Don't modify the system python.
- To view the Users Guide and …

Docs: reviewing local docker-compose steps

---

config/urls.py
core/githubhelper.py
core/views.py
libraries/views.py

Redirect to the latest release when this URL prefix exists on documentation.
Fixes #1084

Add url path to handle /doc/libs/release/*

---

requirements.txt
yarn.lock

This pull request should fix #1182, aside from the yarn dependency.
**update:** included a `yarn.lock` via `$ yarn upgrade`. This bumps some versions up pretty high, so I'd like to get someone to validate that the frontend is working as expected.

update dependencies for security updates

---

templates/adoc_content.html
templates/includes/_footer.html
templates/includes/_header.html

changes contact links for #1221 
changes twitter and github links to icons
also fixes a flashing of the help links in the header on refresh.

footer links and flashing header box

---

config/urls.py
libraries/constants.py
libraries/constants_utils.py
libraries/tests/test_utils.py
libraries/tests/test_views.py
libraries/utils.py
libraries/views.py
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/includes/library_preferences.html
templates/libraries/list.html

There's a good amount of refactoring in this, so this is going to look like a much bigger change than it is. In reality it makes the dispatch code simpler.
Fixes: 
1. Resolved the issue with the libraries pages not redirecting correctly
2. Resolved an issue around categories not being preserved moving from page to page.
The issue with the redirects was there was a tug of war on arriving on /library between the various ways of determining where the user should end up. 
I added a `/libraries/grid/` url and now `/libraries/` determines which list page the user should end up on based on 1) url 2) cookie, 3) the default, same for version preference.  We can probably get rid of dispatch() later. This has the added bonus of allowing reliable linking to a specific list view (e.g. for users to …

fixed issues with libraries navigation, refactors (#1213)

---

config/urls.py
core/views.py
libraries/constants.py
libraries/utils.py
libraries/views.py
templates/libraries/_library_category_list_item.html
templates/libraries/_library_flat_list_item.html
templates/libraries/_library_list_item.html
templates/libraries/detail.html
templates/libraries/includes/library_preferences.html

1. added support for 'release' in library urls
2. fixed versioning not working from the non-grid library list pages
3. fixed library detail user selection of versioning not working
4. unified cookie handling to share across both LibraryList and LibraryDetail

added support for 'release' in urls (#1084)

---

frontend/userguidestyles.css

- removed dark text colors for links in paragraphs, tables, and titles
- removed dark hover color for paragraph links
- removed `font-sans` from `.doc .admonitionblock .icon i`
Needed for boostorg/boostlook#13

Refactor dark mode link styles and nav elements

---

versions/management/commands/import_versions.py
versions/tasks.py

- fixes https://github.com/boostorg/website-v2/issues/1277
- Makes the required POST requests to Fastly to purge the cache for /release/ as described in the issue above.
- Chain the purge function to the import_version task group so that it runs only after all of the `import_version` tasks have completed

Purge Fastly CDN after import_versions.

---

config/urls.py
libraries/views.py
news/tests/fixtures.py
news/tests/test_views.py
templates/admin/library_report_detail.html
templates/admin/library_stat_detail.html
templates/includes/_header.html
templates/libraries/detail.html
templates/partials/avatar.html
templates/users/includes/header_avatar.html
templates/users/profile_base.html
users/models.py
users/templatetags/avatar_tags.py
users/tests/fixtures.py
users/views.py

- fixes https://github.com/boostorg/website-v2/issues/1285
- Use a django tag to render an avatar component.

Create an avatar tag to be usable anywhere we need an avatar.

---

libraries/views.py
templates/libraries/detail.html
templates/partials/avatar.html
users/templatetags/avatar_tags.py

In the library detail page, if a contributor has never contributed before the selected release, give them a "new contributor" flair.

Show flair for new contributors in the selected release.

---

.github/workflows/actions-gcp.yaml

Purge the Fastly CDN in Github Actions, when deploying new code.
I am also investigating an issue related to this topic, and have started a discussion with them.  The TTL of css/styles.css is set to 1 hr in the console. Sometimes it flips back to use the "cache-control: max-age=604800" sent by the Django webserver.  Not every time though.  There are many fastly cache servers, and hierarchical, could be related to that.

GHA: Clear CDN cache after deployment

---

libraries/admin.py
libraries/forms.py
templates/admin/library_change_list.html
templates/admin/library_report_base.html
templates/admin/library_report_form.html
templates/admin/library_report_full_detail.html
templates/admin/release_report_detail.html
users/templatetags/avatar_tags.py

Add library report over all releases.

---

kube/boost/templates/configmap-nginx.yaml

Just discovered the boost.io nginx config is setting "expires 7d" on static assets.   That is the value of 604800 seconds conflicting with the CDN.  Remove that expiration.

Nginx: adjust Cache-Control header

---

config/urls.py
core/views.py
libraries/mixins.py
libraries/tests/test_views.py
libraries/utils.py
libraries/views.py
templates/libraries/detail.html
templates/libraries/includes/library_preferences.html
templates/libraries/includes/version_alert.html
templates/versions/detail.html
versions/views.py

* Fixed issues with releases page and versioning
* Added latest support and version alert
* Updated version alert to link to /release and clarify most recent vs vs "release" selection
* Refactored Libraries and Releases pages to align similar code for reuse.

fixed issues with releases page and versioning

---

templates/base.html

This is related to ticket #1304, the first part of the fix with the library page grid not updated is fixed in the [pull request #1300 ](https://github.com/boostorg/website-v2/pull/1300) which has now been approved.
For ease of review, this should be reviewed after that is merged into `develop`, this is a branch from that. Leaving as draft until then.

Fixed back button library select persistance

---

core/constants.py
core/htmlhelper.py
core/views.py

For now this will wrap based on the view with the assumption, based on our discussions, that User Guide  docs are based on antora and lib docs are asciidocs. Should there turn out to be edge cases we will make some adjustments.
Generated classes will be `source-docs-antora` and `source-docs-asciidoc`.

Added wrappers for docs (#1322)

---

core/asciidoc.py
core/tasks.py
core/tests/test_asciidoc.py
core/tests/test_tasks.py
core/views.py
libraries/models.py

Instead of parsing out the HTML body from the full HTML document.
All adoc parsing now goes through `convert_adoc_to_html`. I removed the `adoc_to_html` task because it was never `.delay`ed, probably because it doesn't necessarily work: it expects content to be passed in a temp file, which might not exist on the worker processing the task. The new function passes the content as a string instead of a temp file.
This removes the `div#header` and `div#content` containers from the output. It's wrong to have IDs in embeddable html because multiple asciidoc outputs might be included on the same page, resulting in duplicate IDs. I couldn't find a place where these containers are necessary, though, because markdown output doesn't include them, resulting in a discrepancy in the output for markdown …

AsciiDoc use the embedded option

---

templates/includes/_header.html

resets standard footer width as the docs are in iframes and won't need special justification.

Set standard footer width

---

core/templatetags/version_select.py
libraries/mixins.py
libraries/utils.py
libraries/views.py
templates/libraries/category_list.html
templates/libraries/flat_list.html
templates/libraries/includes/library_preferences.html
templates/libraries/list.html
templates/partials/version_select.html

* Resolves the issue with libraries not updating on version dropdown selection going back from version to latest
* Fixes edge case of version alert not showing when query params are deleted from location bar
* Adds refactor of version selection drop downs on library preference page and cleans up some unused ones.

Fix library dropdown switching

---

core/views.py
templates/base.html
templates/includes/_header.html

This sets the User Guides to show in an iframe, 
Other changes: 
* Hides the footer in the base template by a context variable.
* Fixes integrity sha for htmx.
* Fixes selector for avatar loading indicator.

WIP - Switched guides to iframe, other fixes

---

core/views.py
templates/docs_libs_placeholder.html

@julioest requested a change to not adding boostbookV2.css on the user guides.

Added skip use boostbook for v2 on antora docs

---

.gitignore
Makefile
config/settings.py
development-tofu/.terraform.lock.hcl
development-tofu/main.tf
development-tofu/modules/github_oauth_client/variables.tf
development-tofu/modules/google_oauth_client/main.tf
development-tofu/modules/google_oauth_client/variables.tf
development-tofu/providers.tf
development-tofu/variables.tf
docs/development_setup_notes.md
docs/non-dev-server-allauth-setup.md
env.template

This is related to ticket #1374, and simplifies the steps for local development environments to have a working login flow for github and google.
The improvements were configuration for the client id and secret for google and github via .env vars instead of having to go through setting up "Social Applications" via the admin interface, and automating the process for creating google cloud projects in which oauth clients can be created. Documentation was adjusted to fit.
That was as far as this could be automated given limitations on both Google Cloud Platform and Github's APIs for creating oauth clients/apps. 
The terraform process can be improved if these tickets see some progress or an API comes about to support this. 
Google
https://github.com/hashicorp/terraform-provider-google/issues/164 …

Reduced steps for local development setup for social media auth (#1374)

---

libraries/github.py

- In the case that it is a string, convert it to a list.
- fixes #1396

The "authors" value can sometimes be a string.

---

templates/news/detail.html

Fixes #861 
Uses tailwind's `break-words` class instead of existing `break-all`. This maintains the character-level breaking on long strings like SHAs, while breaking paragraph text naturally.
Before:
After:

Fix news container word break bug

---

docs/syncing_data_with_github.md
libraries/constants.py
libraries/github.py
libraries/tests/test_github.py
static/css/boostlook.css
versions/management/commands/import_versions.py

Fixes #1034
- Adds a `CATEGORY_OVERRIDES` mapping
- Uses the override in `update_libraries` management command
- Ran `./manage.py import_versions`
- Ran `./manage.py update_libraries`
- Static String had the correct category
- Ensure `update_libraries` is run
- Verify **Container** category is orphaned
- Delete **Container** category

Add category override mapping and use it in library update method

---

libraries/tests/test_views.py
libraries/views.py

Fixes #1224 
- In libraries-by-category view, filter categories to only ones with libraries in the selected version
- Added a prefetch to the query to fix the N+1 query (minor performance improvement)
Before:
After:

Libraries by category view should only show populated categories for selected version

---

users/forms.py
users/migrations/0014_populate_tou_notification_preference.py
users/models.py
users/tests/test_forms.py
users/tests/test_models.py

Fixes #986 
- Adds a new notification preference to the existing `Preferences` model and associated form.
- Adds data migration to populate the new preference
- Adds a new test and modifies several others to reflect the new preference and its behavior
Note the ability to actually send notification will be added post-launch. If the need comes up in the meantime, it would be straightforward to manually trigger a notification to opted-in users.
UI
Data

Profile Setting Option to receive email on material Privacy and Terms changes

---

conftest.py
core/asciidoc.py
core/tests/content/asciidoc.adoc
core/tests/content/asciidoc.html
core/tests/test_asciidoc.py
docker/Dockerfile
justfile
pytest.ini

Related to ticket #1082, this adds support for asciidoc macros to emulate macros from qbk. The `qbk` items below are the originals from the ticket, the `asciidoc` items below are the new ones for asciidocs, and the `html` items below are the output.
qbk: `[phrase library..XX]`
String to use in asciidoc: `phrase::[library,Hi!]`
html: `<span class="library">Hi!</span>`
qbk: `[@/libs/function/ Function]`
asciidoc: `at::/tools/build/doc/html/#_version_5_1_0[B2 version 5.1.0]`
html: `<a href="/tools/boost/boost_1_75_0/libs/algorithm/doc/html/algorithm/">Algorithm Library</a>`
qbk: `[github_pr geometry 1247]`
asciidoc: `github_pr::[geometry,1247]`
html: `<a href="https://github.com/boostorg/geometry/pull/1247">PR#1247</a>`
qbk: `[github geometry 1231]`
aasciidoc: `github_issue::[geometry,1231]` …

Added support for release notes asciidoc macros (#1082)

---

news/notifications.py
news/tests/test_notifications.py
news/tests/test_views.py

Fixes #1428
Previously, we sent a single email with all recipients in the `bcc` field, and no one in the `to` field. Mailgun does not support this.
This PR changes that behavior to send an email to each user using Django's `send_messages` (plural) method.
Note: I wasn't able to confirm this in the Mailgun documentation, but I assume this should not have any cost implications. Sending a "single" email with 100 `bcc` recipients should cost the same as sending 100 emails each with a single `to` recipient.
Another note: I did not test performance of this with many recipients. Probably all of our notification emails should be getting sent in a Celery task... probably a future optimization.

Send individual emails to each notified user

---

libraries/constants.py
libraries/forms.py

- fixes #1398
- alter queries in report forms to ignore sublibraries where necessary.

Keep a list of sublibraries and hide them in reports

---

libraries/constants.py
libraries/models.py
libraries/tests/test_views.py
libraries/views.py

Fixes #1339 
- Adds a constant for the missing README message
- ~`Library.get_description` defaults to this message if no README/library-details.adoc is found~ Update: switched to alternative implementation below
- Alternative implementation would be to use the default message in the view if `get_description` returns `None`
- Adds a test `test_library_detail_context_missing_readme`
I created a bare minimum Library in the shell and visited its detail page. Since there was no README, the default message was displayed.
I then set a cached value for the library's description and reloaded the detail view. The cached value was displayed.

Add missing README message

---

templates/libraries/detail.html

Don't store indexes into a live HTMLCollection, they are not stable over time. Just use the DOM element directly. Use `querySelectorAll() -> NodeList` instead of `getElementsByTagName() -> HTMLCollection` because HTMLCollection does not have forEach but NodeList does.
Fixes #1438

Fix ValidateGitImages when there are multiple broken images

---

templates/news/detail.html

Use the title of the news entry itself for the page title

---

templates/account/signup.html

This allows clicking the label to select the checkbox and is also good for screenreaders.

Associate the TOS label with its field

---

core/boostrenderer.py
versions/releases.py

Follow-up fix for #1171 
It turns out the newest beta release notes have been named `version_1_87_x.html` instead of the expected `version_1_87_0.html` name. This PR creates a fallback strategy that first attempts the `_0` filename, then tries `_x` if the former results in a 404 response.
I wasn't able to successfully test the S3 version of the function, since the beta release notes do not yet appear to be in S3.
For the GitHub version, I added a print statement for debug purposes to indicate we were hitting the fallback url with the `_x` filename suffix.
```python
In [1]: v = Version.objects.last()
In [2]: v.slug
Out[2]: 'boost-1-87-0-beta1'
In [3]: from versions.releases import get_release_notes_for_version_github
In [4]: html = get_release_notes_for_version_github(v.pk)
normal url …
```

Fall back to _x filename for beta release notes

---

versions/tasks.py

We were skipping beta releases when fetching release notes. This PR removes that filter.
I was able to actually import the release notes for 1.87.x locally:

Don't skip beta releases when fetching release notes

---

core/htmlhelper.py
libraries/models.py
templates/admin/release_report_detail.html

- Also delete related per library release notes parsing functions, these functions are specific to the HTML version of the release notes which will be replaced by an adoc version in the near future. If per library release notes are needed in the future, these functions will need to be reimplemented anyway.
- fixes #1470

Remove per library release notes from release report.

---

templates/includes/_header.html

This is antora-specific. Addresses issue boostorg/website-v2-docs/issues/359
Note: This will be 100% fixed when https://github.com/boostorg/boostlook/pull/47 is merged into boostlook, then boostlook copied over to website-v2

refine TOC positioning for legacy docs wrapper based on article presence

---

templates/partials/version_select.html

Fixes #1486 
- Added version number parenthetical in `version_dropdown.html` partial
- Changed version detail template to use this partial instead of duplicating it

Add version number parenthetical to Latest option and DRY up template

---

frontend/styles.css
tailwind.config.js
templates/libraries/includes/library_preferences.html

This is adding the styling to match with changes in the #1489 PR which changes the template to display but disable the dropdown on the categorized listing page. It will appear as:
@rbbeeston the category selection dropdown will now appear with text with the same orange as the version dropdown. Let me know if you want that changed or prefer them to be consistent. 
Enabled dark/light:
Disabled dark/light:

Added styling for disabled state on select dropdowns (#1316)

---

templates/partials/version_select.html

I missed a visual bug that occurs when there is a beta release in the dropdown (I hadn't imported the beta version locally).
This uses the globally available context object `current_version`, which is nicer than the prior implementation anyway.

Fix Latest dropdown option when beta version present

---

libraries/forms.py
libraries/tests/test_forms.py
libraries/views.py
versions/managers.py
versions/views.py

Fixes #1488 
- DRY up various pieces of code getting version queryset for dropdown
- This eliminated the special exclusion of the latest beta from the library detail page

Consolidate version dropdown code and fix library detail dropdown

---

libraries/admin.py
libraries/forms.py

1. Skips graphing commits for library with no commits in the given release
2. Ensures a template is always returned for the report view

Fix report crash issue

---

libraries/forms.py

This is a "blind" fix since I cannot reproduce this locally. Seems like it should fix the crash I'm seeing in the logs though.

Fix issue with slack stats sorting in report

---

kube/boost/templates/configmap-nginx.yaml

Fixes #1514 
Turns out nearly every url was being redirected correctly already. There was one missing. This PR adds it.

Add missing redirect

---

frontend/styles.css

- removes the right-aligned heading 
- addresses issue https://github.com/boostorg/boostlook/issues/42
Preview:

remove unnecessary styles for libraryReadMe header links

---

templates/admin/_release_report_top_left_logo.html
templates/admin/library_report_base.html
templates/admin/release_report_detail.html

Update styling in release report

---

kube/boost/templates/configmap-nginx.yaml

1. Fixes outdated pattern (we now use `/releases/x.xx.x/` instead of `/releases/boost-x-xx-x/`
2. Uses a regex pattern to make the redirect dynamic (was previously only handling 1.84.0
Note this is untested - I don't have a setup to test nginx redirects locally.

Make release version redirect dynamic

---

templates/news/detail.html

In order to show a PDF "preview", this rearrangement allows the uploader to do the following:
1. Upload the PDF as the `attachment` field
2. Export the first page of the PDF as a png (on a Mac, you can do this in preview by choosing Export -> PNG, and then opening the PNG and deleting all pages but the page you want to keep)
3. Upload the PNG in the `image` field
This achieves this result:

Tweak news image and attachment link alignment

---

config/settings.py

- Set `SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT` to `True` so users who have an existing account with a given email will be logged in rather than getting an email about someone trying to register them but they already have an account
- Added `"prompt": "select_account"` so users will be prompted to select a google account even if they're only logged into a single one at the time.
Fixes #1536

Prompt user to select google account and auto-link social accounts

---

docs/commands.md
libraries/github.py
libraries/management/commands/post_release_tasks.py
libraries/management/commands/release_tasks.py
libraries/tasks.py
slack/management/commands/fetch_slack_activity.py
templates/admin/version_change_list.html
versions/admin.py
versions/tasks.py

- fixes #1519
- add button to version admin to execute task
- use @ locked decorator to ensure only one instance of the task is running at any time.
- If a user_id is given to the command, send that user email notifications when it starts and ends.

Add management command to run all necessary tasks after a release.

---

libraries/forms.py
libraries/views.py
templates/admin/release_report_detail.html
templates/libraries/detail.html
templates/versions/detail.html
versions/models.py
versions/views.py

- fixes #1336
- If a libraryversion does not have any known dependencies in the version in question or the prior version, stats are not shown.  There is the case where if a library goes from 0 to n dependencies or vice-versa, that stat will not be shown.  If this is a necessary feature, more work will need to be done to facilitate it.  We are only keeping a many-to-many relationship of LibraryVersions to Libraries so we cannot distinguish between if there are no dependencies or if we were not able to fetch them through the boostdep github action.

Show boostdep data in library/release detail and report.

---

config/urls.py
core/context_processors.py
core/views.py
kube/boost/templates/configmap-nginx.yaml
templates/boost_development.html
templates/docs_temp.html

Add Boost Development page

---

templates/admin/library_report_full_detail.html
templates/community_temp.html
templates/homepage.html
templates/markdown_template.html
templates/review/review_detail.html
templates/review/review_process.html
templates/versions/detail.html

fixes some minor spacing and layout issues on the site, also adds the card format to pages where is was missing, like the privacy policy, for example.
Before
After

minor UI updates

---

core/views.py
templates/base.html

The issue we were seeing was that while pages were being logged, we were still seeing "srcdoc" in the recorded plausible dashboard's entries.
Going through some tests it appeared that certain source types (exhibited in accumulators, lambda) were logging the page *and* "about:srcdoc". 
This was because the code path for those types put the content through doc_libs_placeholder.html which included plausible script tags, while the other pages didn't go through that file. 
The context/content is then passed into docsiframe.html which already imports for the plausible script (as it extends base.html).
This change disables plausible for doc_libs_placeholder.html while still having it enabled by default for all other pages.

Fix plausible logging on doc_libs_placeholder based pages (#1579)

---

frontend/styles.css

removed all references to `#libraryReadMe` css in the styles as they are being managed by boostlook now

removed library readme refs

---

core/htmlhelper.py
core/views.py
templates/docsiframe.html

This PR covers two related issues:
* #1526 
* #1576

Documentation anchor links fixes

---

conftest.py
core/boostrenderer.py
core/githubhelper.py
env.template
justfile
libraries/tasks.py
versions/releases.py
versions/tasks.py

This is related to ticket #1550 
In this PR there is:
* Improved missing s3 key handling in import_release_notes
* Now logs warning instead of an exception being raised 
* Excluded master and develop from release imports. 
* Changed 404 exception to logged warning for library meta data that isn't found.
* Now raises a clear exception when the github token isn't set.
* Sam, you requested a check be made against 'top-secret'. For a value that's explicitly required to be set in the .env in order to function (by comparison top-secret is fine for local django SECRET_KEY) I think it's better to just not set a default value in the first place. We all just need to make sure we delete "top-secret" locally now. It shouldn't occur for new checkouts after this PR. Let me know if there's a reason you …

Improved error processing

---

libraries/constants.py
libraries/models.py
libraries/tests/test_models.py

This is related to ticket #935.
For now it's only set up with the Outcome library. The original ticket mentioned asio works the same way but looking at the Asio git repo it looks like they're using github issues.
There was discussion in that thread of looking at the repo and checking if they're a fork or issues are closed. Given there's no reliably consistent programmatic way to account for each edge case those would introduce and we'd need the overriding url anyway, it's simpler to just check the override map for an existing key as this PR does. 
Happy to change it if anyone feels that's worth the effort and can map out all the edge cases.

Added override functionality for github issues links

---

config/settings.py
config/urls.py
news/constants.py
news/notifications.py
news/tests/test_notifications.py
news/views.py
requirements.in
requirements.txt
templates/news/emails/needs_moderation.html
templates/news/emails/needs_moderation.txt
templates/news/moderation.html

- Email is sent to individual moderators rather than one group email
- Email is HTML with txt fallback
- Email contains magic link to approve news entry without requiring login
- Link expires 24h after it's generated
- Graceful handling of case where news item has already been approved by another moderator
- Non-magic moderation link now redirects to login page instead of 404ing for unauthenticated users
Here's what the email looks like:
Fixes #1586

News moderation email magic links

---

libraries/templatetags/branch_url_tag.py
templates/libraries/detail.html
templates/libraries/includes/dev_master_links.html
templates/libraries/includes/library_preferences.html

This PR adds the links and icons for the master and develop branch on the libraries page.

Master develop icons

---

package.json
templates/admin/release_report_detail.html
yarn.lock

This is related to #1608, adding a speech bubble for the fiscal committee page, and also fixes the layout issues on the git activity page.

Speech bubble for fiscal committee page on release report 

---

libraries/forms.py
templates/admin/release_report_detail.html

This is a work  in progress, related to ticket #1632.
PDF link (PDF file is too large for attaching to github issue)
https://cpplang.slack.com/archives/C0610TPQMAR/p1739492485445449
Notes:
* This is from my local machine, images for Fiscal Committee members aren't retrieved so I added myself with my avatar to show how it will appear. This will appear better on stage/prod.
* For the slack word list, the reason there's a capitalized "Boost" is because that's set up as a merge word. Can be adjusted in the admin interface. 
* We also see multiple "boost" related word combinations, these can be added to the merge list if preferred, but I haven't done it locally. 
* "cloudMergedWord" appears only because it's a test "to" word for a merge for the word "review" in the data. In reality this would …

Multi-page Release Report tweaks (#1632)

---

templates/community_temp.html

Make sure Mailing Lists and Slack text is visible in both light and dark modes

fix text colors on community page refs #1662

---

templates/admin/release_report_detail.html
users/models.py
users/signals.py

This relates to Ticket #1639, to add support for setting the display name from Github SSO data when accounts are set up.
This also update the code to add support for that and the avatar from Google's SSO process.

Pull username/fullname from GitHub (#1639)

---

libraries/forms.py
templates/admin/release_report_detail.html

Line is hidden if value is zero.
That number will drop due to merged commit authors on prod.

Added global new contributor stats (#1676)

---

core/htmlhelper.py
core/views.py
templates/docs_libs_placeholder.html

After discussing what I was seeing with Julio it seems we need to just filter out the libraries' baked in boostlook.css links which will leave us with the `latest` one as it is on the server at any point in time.

Added filter to remove all non-static boostlook.css on library docs (#1684)

---

users/admin.py

Adds `__unaccent` lookup to user display name field for admin search.

Add unaccent lookup to username in user admin search

---

templates/community_temp.html

For narrower browsers, the items will appear vertically

adjust layout/spacing in mailing lists card for mobile refs #1663

---

libraries/views.py

If the author email is not associated with a CommitAuthor, display the name from the User model, if it exists

display author name on library when missing refs #1705

---

core/htmlhelper.py
templates/base.html

This is a work in progress to test some CSS/allow further shared development.
When this is complete I will completely remove the beautiful soup that adds the wrapper class as well as the related styles.
Removed inlined boostlook.css contents and disabled remove-boost-legacy-docs-wrapper (#1707)
There's still a left margin on charconv that will need adjusting but this should be a good jumping off point

Disable boostlook legacy wrapper and remove any inlined boostlook.css style - WIP

---

versions/migrations/0015_drop_review_generated_stub_users.py

A data migration needed to be run _after_ a certain user migration took place. Ran into this on a fresh db install.

Fix data migration dependency issue

---

templates/versions/detail.html

Screenshot only shows removed. Both will show when both exist, or only added will show up if only added has a value > 0.

Add check for dependency addition/removal counts on release page (#1703)

---

users/models.py

Testing locally, I was missing the image for my profile picture, and the entire site (all pages with the header) was crashing. This change makes the profile image property fail gracefully when the image file is missing.

Don't crash for missing profile image

---

kube/boost/templates/configmap-nginx.yaml

Within the 1000's of pages of boost documentation it sometimes happens that visitors go to a webpage that ought to be a directory and should have a / slash on the end.  So, if a page fails to load, nginx tries a second time, adding a slash / , and that often solves it.    A small issue is that nginx is only seeing http connections, and redirects to http.   That will still work for most situations, because http is redirected yet again, at the LB.   This PR modification directly uses https when adding the slash.

nginx slash redirect uses https

---

core/htmlhelper.py

- Removes the no-longer-required wrapper div's id.
- Only adds `boostlook` class to non-Antora docs
- Includes a hack that continues to add "-antora" to pages with no known original doc type (e.g. Beast)
Antora doc looks better:
Non-Antora doc unchanged:

Fix an issue with docs boostlook wrapper div

---

templates/docsiframe.html

- add offset margins to prevent header overlap
- apply larger top margin on mobile devices
- use scrollTo instead of scrollIntoView for better control
References issue #1665
**Mobile:**
https://github.com/user-attachments/assets/b151b2af-89af-44f0-b6a2-4323c5275b94
**Desktop:**

fix docs anchor scrolling with custom margins (#1665)

---

templates/docsiframe.html

This was accidentally left in the html at one point. Removing.

Remove accidental debug line

---

docstailwind.config.js
frontend/styles.css
tailwind.config.js
templates/base.html
templates/docs_libs_placeholder.html
userguidetailwind.config.js

- Standardizes typography by replacing "Noto Sans Display" with "Noto Sans"
- Comments out redundant font family declarations in Tailwind configs
- Updates font variation settings for improved rendering
- Ensures consistent typography across all site templates
- Simplifies font management and maintenance

refactor: replace noto sans display with noto sans

---

templates/docsiframe.html

**Problem**
AsciiDoc documentation (including Charconv) had a regression where anchor links weren't scrolling to their target elements when clicked. This affected both desktop and mobile browsers.
**Solution**
Fixed the anchor scrolling mechanism to properly handle AsciiDoc document structure. Due to markup differences between AsciiDoc and Antora docs, the solution implements two separate scrolling approaches using different JavaScript APIs for each document type:
- AsciiDoc: Uses direct element positioning and manual scroll adjustment
- Antora: Uses container-based scrolling with different position calculation
**Testing**
Tested and confirmed working on:
- Mac, Chrome desktop
- Mac, Safari desktop
- iPhone 16 (iOS 18.2)
**Note**
There is a new that arrises with Safari iOS where the …

fix AsciiDoc anchor links not scrolling to target (Issue #1759)

---

kube/boost/templates/hpa.yaml

There are two django pods in each environment. The autoscaler sets min:2 and max: 8. It will stay at the minimum level unless cpu goes above 50%.

HPA - horizontal pod autoscaler

---

kube/boost/templates/gateway.yaml
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml

Assign an ipv6 address to the google load balancer, so the apex domain redirect also supports ipv6.

ipv6 on GKE Gateway

---

templates/original_docs.html

This turned out to be a simpler fix than expected - adding `<meta charset="utf-8">` to the `head` of the docs template fixed the instances of this shown in the ticket.
Fixes #1815

Add meta charset to library docs template

---

config/settings.py
core/admin.py
core/tasks.py
core/views.py
env.template
kube/boost/values-cppal-dev-gke.yaml
kube/boost/values-production-gke.yaml
kube/boost/values-stage-gke.yaml
kube/boost/values.yaml

Currently the workflow for docs is:
1. Query against Redis which returns nothing
2. Query against Postgres which returns nothing 
3. Item fetch from s3.
This eliminates the redis layer (too high cost for the benefit) and updates the `save_to_database()` function so we now actually store docs which it wasn't previously doing.
The change in terms of DB queries is now: on the first access/crawl by a bot there'll be a write on each page, and from that point on the query on each page will actually return the content instead of returning empty.
For that reason I wouldn't expect this to significantly impact performance, 1 write or read isn't significant, they won't occur in parallel.
For staging the database storage disk size should be ok:
```psql
postgres=# SHOW data_directory;
data_directory …
```

Improve docs performance - postgres caching (#1828)

---

justfile
news/tests/test_views.py
news/views.py

There was a small bug with the code handling expired news moderation magic links. This PR fixes that and adds several tests for this view to prevent future regression.
I recommend going through these steps first on the develop branch to verify it fails with a server error, then on this branch to verify it doesn't crash.
1. Set MAGIC_LINK_EXPIRATION to a short duration (perhaps 5 minutes — it's currently set to 24h).
2. Create a new news item as a non‑moderator.
3. Sign out, and click the link before it expires — you should be taken to the news item’s detail page, and the news item should be approved.
4. Wait until the magic link expires.
5. Sign out (if logged in), and click the now‑expired link:
a. On develop, you should see a server error.
b. On this branch, you should be redirected to …

Fix bug with stale news moderation link and add tests

---

templates/admin/release_report_detail.html
users/models.py
users/templatetags/avatar_tags.py

* Update avatars to add `use_user_hq_image` flag
*  Use high quality Images in fiscal committee list

Fiscal committee high quality images (#1869)

---

core/boostrenderer.py
core/constants.py
core/htmlhelper.py
core/tests/test_htmlhelper.py
core/views.py
justfile
libraries/utils.py
pycharm_debugger.py
requirements.in
requirements.txt
templates/base.html
templates/original_docs.html

This ended up being a bigger change because the code had gotten confusing over time and it was in need of a refactor. Resolves a couple of bugs I saw too. Should be tested extensively that different doc types are rendering as they were before.
* Refactored content retrieval for cleaner code and easier reuse
* Fixed preprocessor encoding type breaking django debug toolbar 
* Added args support for pytest to justfile
* Added canonical uris for versions that aren't the latest
* Performed redirect in docs after `get_from_s3` and `get_from_db` calls (alternative to the PR for ticket #1918)
Fixes:
* Latest redis is now rendering correctly
* Some logic that would have overfit was corrected
* Updated pycharm configuration for pydevd-pycharm 252.25557.178

Refactor docs retrieval, and canonical uri addition (#1857)

---

core/constants.py
core/views.py

This is related to ticket #1929.
Fixed urls missing trailing slashes getting redirected by content view handler, now returns a 404 for nginx to redirect appropriately. Added this as a tuple because we may end up adding more in the future.
This also fixes /releases/latest having the same symptom.
Testing:
Local: confirm the url with a trailing slash works and  there's a 404 for the ones without a trailing slash.
Stage: confirm the url with a trailing slash works and when accessing the url without a slash, that there's a redirect to the url with a slash.

Return 404 for missing release slashes (#1929)
